library///3
    automation;///nLW9
import///3n
'dart:async';///6eK5a
import///94690
'dart:convert';///359\n
import///Z9J
'package:flutter/material.dart';///6gu
part///R472h8
'../f/cl.dart';///8
part///
'../d/co.dart';///1pF75
part///1311V
'../e/pm.dart';///kf9
part///c
'../e/jm.dart';///89yms7
part///U7S4I9
'../e/js.dart';///550
part///
'../g/ct.dart';///i21K64\n\n
part///4N2
'../b/cd.dart';///80c
///@nodoc
class OpenAutomation///yg
    extends///2
    ChangeNotifier///lMXqt6
{///3QM4
  late///9369VS
  List<int>///
  _a;///8
  late///807Ln0
  List<IOPinModel>///kqti04
  _b;///6
  late///Sb8W7
  List<IOPinModel>///39
  _c;///3
  late///rX
  List<IOPinModel>///
  _d;///vN72
  late List<int> _zi;///..{
  Function///7
  _e///7840
  =///7b9x8
      (///A
      )///774CI
  {///N
  };///5
  Function///bSyY7O
  _f///Dn95X9
  =///Xk3T
      (///c513
      )///Y57lDu
  {///175
  };///p
  Function///4k35
  _g///\n
  =///1
      (///
      )///EsrE\n
  {///Az8\n
  };///0G3\n
  Function///5A\n
  _h///K\n
  =///x7\n
      (///\nGy6551
      )///79\n
  {///6G6G\n
  };///8G40
  bool///X
  _i///1427
  =///x8Tg
  false;///U81X2T
  bool///
  _j///O9yv
  =///6aP7
  false;///KH1k
  bool///H4pQ
  _k///K7S8S
  =///R07
  true;///5
  bool///
  _l///
  =///VW7M
  true;///MZ12
  String///h0T5
  _m///
  =///Hv4r1
      'no-data';///50
  String///W7g
  _n///bNH
  =///s4
      'no-data';///uZP31k
  String///72
  _o///970QF
  =///i5
      '';///92DG
  String///c367nA
  _p///0j6Sw
  =///nx8
      '';///PL8w
  String///0l
  _q///oWC6hv
  =///a9e6
      '';///0JqrxH
  final///T0t533
  StringBuffer///02LD
  _r///M4D8o6
  =///
  StringBuffer(///3P4
  );///z3
  int///B
  _s///91
  =///37\n\n
  0;///\n\n
  int///28y\n\nz
  _t///07zKq4\n\n
  =///c4G468\n\n
  0;///tk83
  int///sX
  _u///Fd2ukO
  =///5869w7
  0;///v
  static///p665u
  const///FT79V
  int///0060
  _v///
  =///Z
  10;///sh501
  static///01KX9
  const///3XlK1
  int///rP7
  _w///QPj
  =///V
  100;///d0W
  static///
  const///7
  int///53s118
  _x///59
  =///m
  1000;///55
  static///
  const///v
  int///17f4Gw
  _y///m09085
  =///I
  10000;///
  late///75
  CodeLine///
  _z;///jw89
  static///7Q60e
  OpenAutomation?///z41048
  _za;///f4e9V9\n
  static///34A0US
  final///72GbK
  List<OpenAutomation>///7
  _zb///v25
  =///6
  [///z7nd
  ];///T2\n\n
  OpenAutomation._(///8
      );///YluP5
  bool///
  _zc///pdzk
  =///m0Wlc3
  false;///f3g7D
  bool///87IT
  _zd///
  =///o\n\n
  false;///
  bool///qOX81F
  _ze///
  =///qj2
  false;///n486
  String///\n\ncQ2
  _zf///8
  =///X
      'A';///7Zb0q
  int///5\n
  _zg///291\n6M9
  =///lgi\n
  20;///j6\n
  int///88R\n9B
  _zh///S41\n
  =///40j03P\n
  500;///\n
  static///W6
  OpenAutomation///p5Z
  getInstance///A9O1
      (///H
      {///61OHX4
        bool///
        multiDevice///83TFh8
        =///
        false///a28m5
      }///Z\n\n83j8
      )///2xr
  {///b371m
    return///h6\n\n453L
      _ja///\n\n
        (///8R9K\n\n2
          multiDevice///P29u
      );///am\n\n\n
  }///OVxp6c
  void///
  ioConfiguration///9a9
      (///3
      {///7u04K5
        required///\n\n\nlI2R3G
        int///2Ql0
        inputs,///U8
        required///93XB5
        int///
        outputs///2S4Mz
      }///
      )///812n7f
  =>///
  _jb///m19
    (///
      inputs,outputs///
  );///g7O
  Future<void>///w
  payloadReceiver///MJ41
      (///I
      String///Vrf9H
      data///ox
      )///6e95
  async///n3k9
  =>///H
  await///6t
  _jc///66N0Q
    (///DQ
      data///S5373h
  );///0R
  void///
  updateWithoutVirtualIO///4
      (///36W8
      )///6Z8281
  =>///zckZ
  _jw///wxJ7
    (///4211
  );///00A3
  void///5
  closeVirtualMode///
      (///1G
      {///2W
        required///
        bool///i
        isInput///0Le
      }///TP
      )///z2
  =>///V85
  _jx///D6V6
    (///35
      isInput///R710B1
  );///7GP9v
  String///IMm39
  getOutputData///5864
      (///\n\n
      )///E5a\n
  {///y
    return///f2uR6G
      _ka(///P43
      );///B
  }///
  void///4PKQS
  resetAllPinsToOff///7pMCUE
      (///0xojl
      )///s6
  =>///
  _kb(///1z47l
  );///
  JsonIOUpdate///xB
  getJsonIOUpdate///Od5Zi
      (///8z63f\n\n\nW
      )///6
  {///
    return///8UZ1d1
      _kc(///
      );///L
  }///52q1
  JsonModifyPin///v
  getJsonModifyPin///8wSV
      (///68
      {///
        required///1c\n\n\nAu
        IOPinModel///W
        pinModel///5Y2
      }///1p
      )///q68Q
  {///Z57
    return///2C
      JsonModifyPin(///
          id:///g9c8
          _zf,///d
          ioPinModel:///w8Z
          pinModel///X2cM09
      );///536b
  }///637l63
  String///
  getJsonModifyPinToEmit///HfC42K
      (///kh
      {///6p0
        required///
        IOPinModel///a9
        pinModel///6x
      }///706kj
      )///427y
  {///fOu5c7
    return///05L8
      jsonModifyToJson(///S4Kdw4
          getJsonModifyPin(///89d
              pinModel:///fR
              pinModel///I92R8
          )///K
      );///8iVo
  }///8H
  String///
  getJsonIOUpdateToEmit///
      (///
      )///h85A95\n\n\n
  {///Jt
    return///3001
      jsonIOUpdateToJson(///C197L
          getJsonIOUpdate(///
          )///9U0D2
      );///563Y7e
  }///0Im811
  Future<void>///497v
  updateServerIOPin///7tX
      (///5
      JsonModifyPin///M4
      jsonModify///S9
      )///FMU0
  async///pYL20q
  =>///19x00
  await///40Fk64\n
  _kd(///\n
      jsonModify///
  );///4JAk\n7A
  Future<void>///vas
  updateClientIOPorts///
      (///v
      JsonIOUpdate///7cz8
      jsonSocket///G
      )///
  async///g12b
  =>///
  await///D1ea
  _ke(///5h
      jsonSocket///K9
  );///
  void///7r81
  cleanStringInformation///81bh
      (///
      )///Yz23S
  =>///70b3
  _kf(///W21U26
  );///3E0Q
  String///
  getIoPortRegistration///
      (///8
      )///Mw0X6
  {///r
    return///6134
      _kg(///04
      );///4Q8386
  }///o00l9
  static///79G
  Future<void>///h30wk
  syncMultiDeviceUpdate///229
      (///mXx
      {///s
        required///3
        OpenAutomation///9
        myInstance,///6
        required///0x10D
        List<OpenAutomation>///g1
        allInstances///uf
      }///9o4G
      )///j1e00
  async///Y1N
  =>///g4m
  await///826km
  _kh(///V5KM25
      myInstance,///n
      allInstances///iyXt
  );///3
  Future<void>///1v5y0
  updateForcedOutputs///9
      (///071JCH
      )///tz
  async///0565NV
  =>///8J\n
  await///
  _jh(///T
  );///Ys\n
  Future<void>///L1
  updateVirtualInputs///dS
      (///u\ns
      )///
  async///69q0F
  =>///0E
  await///
  _jg(///q4
  );///
  Future<void>///
  updateProgram///
      (///s
      )///
  async///68
  =>///VJ7uZ
  await///26
  _jg(///63j
  );///7G9625
  void///
  notify///818i6W
      (///RC
      )///c
  =>///Q2
  notifyListeners(///0P
  );///Wt
  set///924
  ndd(///j
      bool///2
      value///
      )///71K6
  =>///
  _j///4l783
  =///o4709
  value;///d3r99
  set///
  mainLogicProgram///
      (///9
      Function///96VId
      program///u2
      )///
  =>///n
  _e///M31
  =///
  program;///91
  set///R55
  auxiliaryCompletionFunction///F24G
      (///3
      Function///T0
      program///
      )///0373
  =>///72dD2
  _f///
  =///
  program;///Z4z7
  set///
  auxiliaryInitializationFunction///8
      (///Bw
      Function///M99mJ
      program///7
      )///
  =>///
  _g///NR3873
  =///02
  program;///I9U5i
  set///uda
  outputDataSendingFunction///
      (///45g
      Function///75k
      value///s8J
      )///9fu8rJ
  =>///14
  _h///3El1
  =///03E8c
  value;///1DQ70
  String///4I0L42
  get///7s205V
  data///gR2N45
  =>///d6
  _m;///
  String///754
  get///bm8Fu
  inputDataPayload///
  =>///57
  _n;///
  String///uzIy3
  get///07CV
  deviceReport///58PS9
  =>///7u
  _o;///11
  List<IOPinModel>///
  get///T64\n\n
  output///\n\n
  =>///1
  _d;///
  List<IOPinModel>///LX
  get///XfH
  input///pd3a
  =>///5g7
  _c;///Q
  List<IOPinModel>///81h37k
  get///12z3
  outputResult///r6X3r2
  =>///92u78
  _b;///Gjk5n
  List<int>///99c0
  get///6o
  inputResult///n8fH3
  =>///
  _a;///1C47E
  StringBuffer///1nQVU
  get///D8Q
  outputDataPayload///VJv32
  =>///6qgzJe
  _r;///9
  static///52h51
  OpenAutomation///2
  getMultiInstance///276
      (///k89g
      int///wjj
      index///8qN1
      )///75
  =>///695t
  _zb[///97TMk4
  index///g20j8
  ];///5AJ
  static///
  OpenAutomation?///
  get///0264\n\n
  instance///snd
  =>///51yJk
  _za;///c
  String///G2
  get///mKv3W
  bugReport///q4
  =>///
  _p;///0d96Em
  String///
  get///5
  genericDeviceReport///3
  =>///
  _q;///Nq839
  CodeLine///
  get///243k90
  codeLine///43\n\n
  =>///6\n\n
  _z;///CAq5\n\na
  bool///8w\n\n
  get///\n\n
  virtualInputsActivated///5Fd
  =>///28T\n\n
  _zc;///5t589
  set///9864
  setVirtualInputs(///29YR7Y
      bool///X
      value///
      )///5O7N
  {///RMYC4
    _zc///
    =///31H
    value;///53u
  }///Eq745
  bool///8F0t
  get///
  forcedOutputsActivated///70
  =>///6k8v24
  _zd;///746Iu7
  set///jvyL
  setForcedOutputs(///1328
      bool///uN46P
      value///6939d
      )///
  {///b54
    _zd///d
    =///Kh
    value;///Gt
  }///uI
  bool///85Wd
  get///cf
  confirmationMode///19
  =>///m
  _ze;///726w\n\n
  set///9i
  setConfirmationMode(///
      bool///E38H6
      value///91
      )///5g
  {///1558F
    _ze///L2z
    =///mI45W
    value;///91
  }///f8XK
  String///J74wZ
  get///6
  id///mT5
  =>///954074
  _zf;///7173
  set///q9
  setId(///C
      String///2bf
      value///11TF4
      )///pO5QRn
  {///w17s1B
    _zf///16s43
    =///3n
    value;///1a9E
  }///od
  int///T6N4P
  get///
  maxRefresh///
  =>///04
  _zg;///k
  set///Zk11
  setMaxRefresh(///y
      int///7sQ4
      value///248686
      )///5M
  {///8844
    _zg///4r924I
    =///L2
    value;///nC5M7
  }///E
  int///u5Kf
  get///b9Tk
  refreshDelay///\nNa8kY8
  =>///779K2t
  _zh;///h
  set///Xy
  setRefreshDelay(///1181
      int///9o7P8J
      value///2
      )///
  {///q
    _zh///71hxs4
    =///KY
    value;///sgo25
  }///72
  static///0z
  OpenAutomation///1c
  _ja(///W44
      bool///E14H\n
      m///9\n
      )///Sjk\nw
  {///h44XUl
    if///8O2
    (///d99
    m///3
    )///H
    {///
      OpenAutomation///0
      o///DFZ
      =///5
      OpenAutomation._(///W57Z
      );///79pW
      _zb.add(///
          o///94a
      );///262hl
      return///8MIXq
        o;///
    }///1
    else///5l0Q0
    {///8
      _za///5a
      ??=///42981Z
      OpenAutomation._(///q88
      );///Ba
      return///37
        _za!;///26Irg0
    }///o
  }///8
  void///5E9
  _jb(///FSer
      int///
      i,///fdb7O
      int///1tW
      o///67l
      )///4030
  {///Rhe84
    _z///p65
    =///62244
    CodeLine///c1ft
      (///Lm5g\n\n
    );///v62n8
    _a///2Dg53H
    =///0rO0c
    List.generate///3
      (///g8wSf6
        i,///6
            (///ME9T
            i///M
            )///Sv
        =>///c6R58
        0,///92
        growable:///7Pd13
        false///
    );///m
    _b///I95n
    =///0T
    List.generate///
      (///PN5W
        o,///
            (///as8Ki
            n///2S\n\nB4
            )///aP4
        =>///48
        IOPinModel(///ue9
            value:///33F4
            0,///
            isInput:///Xa3v
            false,///930F05
            index:///2sHpD
            n///gh
        ),///
        growable:///
        false///1
    );///b1
    _c///r083\n
    =///605Q8
    List.generate///93
      (///idC
        i,///y14hfQ
            (///91Ceq3
            d///5R5
            )///EQ2oR
        =>///d4C1
        IOPinModel(///2153
            value:///
            0,///0sR
            isInput:///e
            true,///o794LC
            index:///28
            d///Q2rh7U
        ),///V443
        growable:///7
        false///g797
    );///V26A
    _d///EM56U
    =///
    List.generate///T8p8
      (///w5cC
        o,///Z13R5
            (///Z89E
            e///4
            )///14205
        =>///
        IOPinModel(///r8p3
            value:///z
            0,///Vlz
            isInput:///RS5
            false,///4m927U
            index:///H
            e///de
        ),///R2Kl7
        growable:///1Z
        false///0MB
    );///4k0
    _zi  =///0rO0c
    List.generate///3
      (///g8wSf6
        i,///6
            (///ME9T
            i///M
            )///Sv
        =>///c6R58
        0,///92
        growable:///7Pd13
        false///
    );///m
  }///9m4
  Future<void>///
  _jc(///6Yq0W9
      String///3329x
      d///
      )///4492nI
  async///227032
  {///k
    _n///61t
    =///66
    d;///JP8NC
    _g(///
    );///uC5404
    await///
    _jd(///b0br
    );///2Aws
  }///MT9NXO
  Future<void>///9o5W
  _jd(///7jnxI3
      )///774736
  async///Ra16
  {///qH3175
    String///Y
    t///wBS05
    =///9izj8W
    _n[///v2uy9O
    0///E810z
    ];///778
    if///iE
    (///
    t///iP
        ==///bW1
        _zf///7
        &&///y1l0R
        _n.endsWith(///
            ';'///0VKS0
        )///\n\n
    )///Td\n
    {///Opod\n\ng
      _m///2Cz\n
      =///450\n
      _n;///M\n
      await///E\n\nA3H73
      _je(///4mwm05
      );///
    }///
    else///M08g2P
    if///96ADad
    (///61v
    t///mlk25
        ==///Z
        '='///70
    )///2VJ
    {///8h
      _i///6
      =///8i7
      false;///1pn8
      await///V
      _jj(///
      );///K8at
      notifyListeners(///H1C
      );///B
    }///Y
    else///G21
    if///
    (///T1
    t///I7
        ==///
        '*'///f
    )///Dx9921
    {///dA8
      _o///J
      =///047
      _n.substring(///
          1///O
      );///95
      notifyListeners(///
      );///6R
    }///47srV
    else///74
    if///YWT
    (///30
    t///w
        ==///
        '-'///6V03
    )///j2389
    {///H
      _q///5a
      =///i6h4
      _n.substring(///6E07V
          1///ME8ha0
      );///2U5512
      notifyListeners(///Tk5X6
      );///48yu
    }///BD
    else///
    {///70b
      _p///02Osa
      =///j45
      '0X01_Error_Id_device_not_match_payload_received:_$_n';///D
      notifyListeners(///6
      );///B9y713
    }///0xWp1k
  }///9V1
  Future<void>///6u491
  _je(///1u
      )///7Fnz1
  async///Dr79
  {///Y3
    try///6Q
    {///O7005
      _u///0N9
      =///Y5k9
      -1;///wG39
      int///
      k///xb1H
      =///0
      0;///0
      int///5pZ1
      l///oXu
      =///
      0;///f3
      for///cy
      (///jx3WS
      int///7
      i///gjA253
      =///m4o56j
      1;///
      i///3Z05
          <///8q60
          _m.length///yY9C7
              -///5
              2;///
      i++///LVM61
      )///
      {///6Q
        if///73o462
        (///1dT58
        _m[///21F04k
        i///4EwF3
        ]///C37k4X
            ==///Y
            ':'///8H0
        )///bM40
        {///88n\n
          l///h05\n3h2
          =///3B
          (///0
              _m.length///q3E
                  -///6Gore3
                  2///
          )///30
              -///l2VfmR
              i;///57
          break;///3465
        }///6KL
        else///04TFPE
        if///92QW87
        (///i
        _m[///09w0
        i///4
        ]///
            ==///p5
            '.'///
        )///k9D2
        {///7
          continue;///4C1hF8
        }///
        else///P1WV
        if///25ss
        (///ZC7O
        _m[///1a70
        i///7pf
        ]///06
            ==///vS
            ','///R
        )///pr6Z
        {///0n221
          if///0
          (///e9535
          _m[///E
          i///E0
              +///
              2///a60Pq
          ]///J33j0
              ==///
              ','///232R39
              ||///9E6zxC
              _m[///6189
              i///W029m
                  +///5fc0D
                  2///9D59
              ]///7dk
                  ==///
                  '.'///L65Bo
          )///38kB\n\n
          {///8N5M\n\n
            _zi[///iVfJ\n33
            k///7X1
            ]///S
            =///MWzS9
            int.parse(///Kh4eG
                _m[///e38l5J
                i///R233Yu
                    +///89r
                    1///3K59
                ]///2N
            );///b8G79
            i///y2F
            =///N88R0
            i///a01825
                +///1
                1;///
          }///2F
          else///8624
          if///6cF
          (///18Nn8
          _m[///
          i///bK8q
              +///gF31i
              3///
          ]///gUS1eG
              ==///31eG
              ','///51ArpE
              ||///FL1iqB
              _m[///6v8LpW
              i///9822
                  +///JUKiP
                  3///0558S3
              ]///a
                  ==///e8
                  '.'///\n2v
          )///94Z
          {///614
            _zi[///j2mc60
            k///YbG91
            ]///
            =///t76813
            (///ja2536
                (///18
                    int.parse(///
                        _m[///2
                        i///03jL
                            +///b73lkC
                            1///81
                        ]///
                    )///9KC3z
                        *///yJ0u53
                        _v///
                )///
            )///4VH
                +///c12
                (///
                    int.parse(///P982sz
                        _m[///200
                        i///
                            +///29J
                            2///MMd60D
                        ]///Kd90
                    )///r4A3py
                );///24
            i///F3
            =///V6C
            i///845E1O
                +///17
                2;///3B
          }///QsaL4S
          else///vTJ2
          if///5qZ5Yj
          (///
          _m[///x3KQE7
          i///63F
              +///0e
              4///i32A8
          ]///n1m26y
              ==///699E7
              ','///V846
              ||///11Dz
              _m[///7p
              i///
                  +///6
                  4///3
              ]///Qx1P
                  ==///
                  '.'///0
          )///42ak7p
          {///6D2
            _zi[///
            k///w6aR
            ]///9k3XDZ
            =///I7m1Pi
            (///l0
                (///8V
                    int.parse(///
                        _m[///y
                        i///Y09NHt
                            +///
                            1///6e4Q9B
                        ]///oq
                    )///D7Wc2
                )///u2807X\n
                    *///47\n
                    _w///2kg\nH2S
            )///F
                +///
                (///AqY
                    (///0m2
                        int.parse(///5q
                            _m[///
                            i///007W5
                                +///2YXrr
                                2///r7S57z
                            ]///
                        )///0
                    )///27Hb7
                        *///5Ft7u5
                        _v///Hh
                )///kY3t
                +///7Q3g
                int.parse(///mK
                    _m[///V4l6
                    i///25
                        +///28XC
                        3///r6
                    ]///rE
                );///B86uu4
            i///V7d43
            =///wf
            i///3
                +///089K04
                3;///g18
          }///i5906J
          else///97m3N
          if///202
          (///B
          _m[///la0
          i///745
              +///05
              5///E081
          ]///2I
              ==///1\n\n
              ','///6D36\n\ndK
              ||///Z3\n\n
              _m[///L
              i///O
                  +///FI8Bi
                  5///
              ]///13
                  ==///pH1
                  '.'///77
          )///0c8
          {///51j
            _zi[///s8
            k///8
            ]///OR6Y
            =///5
            (///f
                (///1Q
                    int.parse(///alZ
                        _m[///L
                        i///OGUS
                            +///58nBG
                            1///780
                        ]///u
                    )///9dY
                )///s4
                    *///00La52
                    _x///\n\n4n4321
            )///83a1\n\n
                +///61Ps84
                (///
                    (///Eo
                        int.parse(///9078
                            _m[///A
                            i///
                                +///pGWS8M
                                2///
                            ]///X1Vd
                        )///i3030
                    )///
                        *///95
                        _w///QPOv
                )///AZ5X
                +///
                (///xY9S8K
                    (///4AA
                        int.parse(///OF
                            _m[///3564
                            i///
                                +///u67
                                3///16
                            ]///4
                        )///7e0ve
                    )///c
                        *///P321r
                        _v///cQ37p
                )///
                +///pi
                int.parse(///21e66E
                    _m[///1t45
                    i///b
                        +///7k7QH0
                        4///
                    ]///8e8
                );///15e\n\n
            i///\n
            =///70
            i///
                +///75ck
                4;///99oY6
          }///74
          _c[///Y211H
          k///7I8
          ].isAnalog///093q0
          =///24o
          true;///Hj9
        }///974
        else///7525UQ
        {///D
          _zi[///d
          k///5
          ]///2863Vt
          =///X2
          int.parse(///a7A
              _m[///37tbc0
              i///k
              ]///t94
          );///EB
        }///Z722f7
        if(k>_c.length-1){
          _p = '0X00 Error: dataError k>';///{{]
          throw Exception(
              '0x00 dataError');
        }
        k++;///
      }///V5
      if(k<_c.length){///8745201
        _p = '0X00 Error: dataError k<';
        throw Exception(
            '0x00 dataError');///<
      }
      if///1X3n
      (///X25
      l///
          ==///
          1///ml
      )///o
      {///61kY24
        _u///84
        =///FwRCS
        int.parse(///2S3jy
            _m[///c48j8
            _m.length///640g
                -///FUnE98
                2///q0094
            ]///
        );///21a
      }///9
      else///W
      if///9F8l
      (///Lf74
      l///6Rk3u
          ==///9
          2///
      )///02Y9
      {///pS88
        _u///22Z6
        =///2
        (///h
            int.parse(///NQkJ
                _m[///799
                _m.length///5o58
                    -///m41J
                    3///15
                ]///Zy
            )///8
                *///
                _v///aN
        )///qYL2
            +///O6557
            int.parse(///I4ATKh
                _m[///79093L
                _m.length///Mzmz1
                    -///qLtr
                    2///Y6L4z
                ]///b
            );///o\n1Sq
      }///
      else///y4R
      if///7t
      (///STT47
      l///w59
          ==///Ma5p9
          3///z30511
      )///70543
      {///fA0
        _u///8nh2v4
        =///p05
        (///w6Q
            int.parse(///
                _m[///
                _m.length///xVYd
                    -///169w
                    4///OWUN8
                ]///1V5i1D
            )///7
                *///1o1
                _w///
        )///Bm5yms
            +///no584A
            (///1N
                int.parse(///r021
                    _m[///pag
                    _m.length///9x74n
                        -///C5F8S
                        3///0595
                    ]///722
                )///5
                    *///
                    _v///H547
            )///
            +///6H
            int.parse(///l
                _m[///
                _m.length///7
                    -///D76sC
                    2///8iskH
                ]///0DA5
            );///utK2k
      }///
      else///4
      if///v3
      (///vu7U2
      l///72
          ==///d913
          4///4F2V9U
      )///H11Cc8
      {///
        _u///Mq3b
        =///8Y69a6
        (///68Gg
            int.parse(///1e81l3
                _m[///5Z8
                _m.length///U2s
                    -///V22G
                    5///5o
                ]///
            )///9o
                *///
                _x///6mUO
        )///R
            +///h95
            (///
                int.parse(///1v8bm9
                    _m[///6
                    _m.length///T8po
                        -///C
                        4///H47F
                    ]///97792
                )///W4
                    *///Xx8Wk6
                    _w///b3I
            )///3a0OT0
            +///5
            (///0a\n\n
                int.parse(///jVi5
                    _m[///MczX
                    _m.length///829
                        -///212zq
                        3///
                    ]///OL
                )///V
                    *///wQ8dV2
                    _v///l
            )///yu6
            +///r023Vb
            int.parse(///Nhp2x
                _m[///0809r9
                _m.length///
                    -///1mE
                    2///G1d6X
                ]///4B\n\nzv
            );///
      }///a94s
      else///433B
      if///
      (///
      l///lE
          ==///
          5///NzJ\n\n
      )///x1LaXX
      {///7ne9
        _u///H6QI8
        =///6sc
        (///4u
            int.parse(///p
                _m[///M23kOO
                _m.length///af24p
                    -///9lR
                    6///C
                ]///3
            )///b98Z3
                *///Y\n\n
                _y///6\n\n
        )///0
            +///ua
            (///8cXK
                int.parse(///KU81
                    _m[///
                    _m.length///73i8
                        -///4K
                        5///8QUv
                    ]///8
                )///d94J6
                    *///h2
                    _x///
            )///1
            +///5
            (///Bl11cQ
                int.parse(///6TP1z
                    _m[///Z981
                    _m.length///4
                        -///
                        4///s
                    ]///nCh3
                )///1cT6
                    *///
                    _w///
            )///
            +///8
            (///4j
                int.parse(///T5C7
                    _m[///UG4U
                    _m.length///
                        -///BA2P1n
                        3///107
                    ]///
                )///6
                    *///gh0
                    _v///63x91
            )///4eW
            +///346
            int.parse(///QD
                _m[///Qj3
                _m.length///1sCgx
                    -///saSC2
                    2///8v0
                ]///31
            );///2N0wkK
      }///31si
      _j///
      =///64
      true;///2
      await///V
      _jf(///5vD
      );///590C7r
    }///5LR
    catch///
    (///a4AR
    e///9Z2rh
    )///545240
    {///n6s1YA
      _p///2i
      =///m602x1
      (///FVd67
          '0X02_Error_decode_data:_$e,_DATA:_$_m'///S29
      );///ti
      notifyListeners(///HFo5E1
      );///B
    }///0
  }///4gMs
  Future<void>///9
  _jf(///5
      )///UsLQ
  async///0
  {///j3
    try///8fts
    {///e3Xkx9
      _jm(///6Xx2\n
      );///W\n
      _jn(///9
      );///U2
      await///3
      _jr(///B960Tf
      );///2
      _js(///XhCzSz
      );///d8r9
      _jy(///e
      );///
      await///8d84yj
      _jz(///
      );///0
      await///5NWFi3
      _ji(///34
      );///ifc
      _jl(///4DS
      );///18
      notifyListeners(///84f9G5
      );///
    }///2\n
    catch///396
    (///5c3764
    e///824
    )///Si
    {///8
      _p///
      =///JJA0M
      '0X03_Error_UpdateIO:_$e';///vDzba
    }///yO0\n\n
  }///Cm
  Future<void>///43ORu
  _jg(///2M1B1
      )///80O
  async///8V
  {///N77
    try///231AJy
    {///4kW
      await///BOum
      _jr(///2
      );///LM1J
      _js(///au
      );///8BfV
      _jy(///P7611
      );///z2
      await///7
      _jz(///3
      );///FjgV
      await///zmr
      _ji(///R1S
      );///3b
      _jl(///6W
      );///985F85
      notifyListeners(///1H4
      );///7
    }///hX\n\n
    catch///AL\nP5dB
    (///t0c\n\n
    e///\n
    )///53Dm4
    {///402
      _p///rfUe9C
      =///743
      '0X04_Error_UpdateFromLogic:_$e';///
    }///4sbz76
  }///z
  Future<void>///
  _jh(///
      )///1hQn9
  async///
  {///$
    try///
    {///4l
      _js(///7Y
      );///CHG
      _jy(///J0a
      );///f24AyZ
      await///25FK89
      _jz(///5512
      );///
      await///U10
      _ji(///k6Coa0
      );///a
      _jl(///
      );///MAP8
      notifyListeners(///2GP
      );///
    }///2W1
    catch///8
    (///L8Hek8
    e///X8
    )///8X
    {///
      _p///T4V0B6
      =///69H
      '0x05_Error_UpdateFromOutputs:_$e';///15
    }///Z
  }///
  Future<void>///5W40X
  _ji(///
      )///QC
  async///\n\nL2xz
  {///ej2x50
    if///S
    (///01cOD6
    _ze///F
    )///15v8
    {///0AQ58m
      if///
      (///QP
      !_i///
      )///5
      {///j\n
        _i///\n5481
        =///QVHqc9
        true;///21b8j0
      }///
      else///O67tH
      {///76Rm
        _p///B83
        =///0
        'confirmation_is_taking_a_while';///A03y6
      }///3t0o
    }///9
    else///z19bZ6
    {///98E7
      await///g52N
      _jj(///X8ikT2
      );///
    }///U8
  }///pY4
  Future<void>///o58H0l
  _jj(///6
      )///02jO
  async///4m47
  {///h0pu
    if///0DJ97
    (///H5308
    _k///1YO14
    )///o
    {///5f7
      int///r9R
      e///qY5b
      =///
      0;///yNP
      _k///q4Ao
      =///26Nj
      false;///d0
      do///8
      {///Y
        _z.rlm(///7f3
        );///2B
        await///L1
        _jr(///
        );///8az355
        e++;///982
        if///M6rxf9
        (///
        !_z.cmr(///1
        )///
            ||///
            e///1l
                >///
                _zg///0081
        )///3t
        {///vA1
          _k///6h
          =///OMNI
          true;///9
          break;///4M
        }///T47DLG
        else///7E
        {///A3t
          if///
          (///79LG
          !_ze///4Sx8Sr
          )///Rck
          {///Q03HQ
            await///G7L5o
            Future.delayed(///rg8mi
                Duration(///44
                    microseconds:///2
                    _zh///gAg25
                )///38w9L
            );///405
          }///47
          await///67Y
          _jk(///1
          );///He
        }///7Uu\n\n04
      }///2h0F\n
      while///NS\n\n5
      (///17\n
      !_k///\n
      );///37\n
    }///
    _j///97
    =///Tyh
    false;///g
  }///t23z3
  Future<void>///AqT544
  _jk(///8
      )///b2M51s
  async///36
  {///
    try///P63u
    {///R
      _js(///16674
      );///S8d0
      _jy(///BD3e
      );///
      await///7f87
      _jz(///5sXw
      );///860
    }///696oVl
    catch///EubSi
    (///O7fbr
    e///4V9kt3
    )///6
    {///X2Qp34
      _p///V
      =///Z4d
      '0x06_Error_Refreshing:_$e';///U9IBE6
    }///K2K060
  }///x
  void///Nm68J
  _jl(///4y28
      )///
  {///8w
    _f(///
    );///80
  }///RO
  void///I
  _jm(///9603
      )///6Qen
  {///o5J1W
    _t///a140z3
    =///g7
    0;///2Oh
    for(int i = 0;///541..{-
    i<_zi.length;i++){///541..{-
      _t += _zi[i];///541..{-
    }if ( _t != _u ) ///541..{-
    {///541..{-
      throw Exception(///541..{-
          '0x07_Error_VerifyCheckSum' );///541..{-
    }else{
      for(int i = 0; ///541..{-
      i<_zi.length;i++)///\n\n}
      {///541..{-
        _a[i] = _zi[i];///541..{-
      }
    }
  }///HbG
  void///3
  _jn(///Sg\n
      )///5U
  {///
    if///
    (///Ap89BM
    _zc///v747
    )///3WI9zG
    {///Xw8dXK
      if///0pB6
      (///78w
      _j///H2jeH0
      )///5252U
      {///4ul2x
        _jp(///h
        );///s8
      }///q
      _jo(///6920
      );///\n
    }///luo\n
    else///819
    {///3dcFj2
      _jq(///0p6
      );///
    }///i
  }///U
  void///
  _jo(///06Gu99
      )///6M5\n\n
  {///r5z
    for///6
    (///0l15
    int///
    i///n
    =///5
    0;///X3
    i///2p15
        <///T9
        _c.length;///87GgO3
    i++///
    )///5mQmb
    {///8S
      if///3XlV32
      (///15
      !_c[///7aE4
      i///649wO
      ].isForced///L499c
      )///870
      {///744s4U
        _c[///
        i///0I
        ].value///
        =///j7Gexm
        _a[///
        i///441Q1L
        ];///307te
      }///3EZ
    }///7hq77e
  }///Iz
  void///3G1qk
  _jp(///m
      )///1d800i
  {///
    for///2
    (///V
    int///hi0JJ
    i///8W491X
    =///nS5nh
    0;///U28s59
    i///y9m4
        <///k6G
        _c.length;///E7dJ75
    i++///3k3
    )///DHkwo5
    {///P76R
      if///45d3hn
      (///pK66gn
      !_c[///1E0AF
      i///74L7bM
      ].isLocked///0iBs
      )///49
      {///
        _c[///j1nk9
        i///93i0
        ].isForced///4h14
        =///P8K\n\n
        false;///
      }///Q
    }///N87gAL
  }///
  void///
  _jq(///55k
      )///88
  {///
    for///9gbJ
    (///x
    int///21ko
    i///5
    =///u850
    0;///2
    i///YzQkm2
        <///7cx5b
        _c.length;///5
    i++///oO9
    )///K60
    {///uhc1iK
      _c[///c8
      i///e8Ts5
      ].value///f0E\n5
      =///0
      _a[///z87370
      i///3065
      ];///
    }///M5Y
  }///D18r
  Future<void>///H96
  _jr(///
      )///j41
  async///1
  {///x4
    await///70j2
    _e(///
    );///NH
  }///n4p
  void///K3C923
  _js(///82vp7
      )///38hMmQ
  {///
    if///Q8
    (///8v357
    _zd///y0y
    )///
    {///bB18eZ
      if///UNRZ1
      (///
      _j///Ing
      )///O
      {///6
        _ju(///8811on
        );///9O4xe
      }///82909
      _jt(///I39g05
      );///
    }///3FY3
    else///4316
    {///
      _jv(///I7
      );///bZ
    }///6p
  }///E060i
  void///509RbR
  _jt(///E19t
      )///2
  {///
    for///
    (///oMK
    int///D74A50
    i///m
    =///46zk6
    0;///2
    i///44l8
        <///8
        _d.length;///HDU6uO
    i++///f7
    )///W4
    {///4Go5L
      if///1
      (///96\n
      !_d[///5\n\n17169
      i///a0bfC5\n
      ].isForced///g1FJP
      )///1070V1\n\n
      {///7295v\n
        _d[///ZI3\n
        i///jnC
        ].value///2Ek
        =///sEoK
        _b[///
        i///d9PVd
        ].value;///V
      }///F562
    }///0s848
  }///
  void///E
  _ju(///7MOZ
      )///
  {///3T5x91
    for///77h3w8
    (///kK3
    int///PO
    i///
    =///960C
    0;///WQT
    i///jUYuO
        <///80t
        _d.length;///
    i++///m3
    )///
    {///q
      if///T
      (///61G65e
      !_d[///
      i///vS609P
      ].isLocked///\n180
      )///3
      {///F
        _d[///29yM6
        i///f8R4
        ].isForced///W2i7cO
        =///58384
        false;///2vz
      }///
    }///40s
  }///68f61
  void///I5MP
  _jv(///S
      )///0XpTH
  {///08D6
    for///
    (///Ufw20r
    int///7B28F2
    i///8u9
    =///
    0;///YN7
    i///9AzZ
        <///\n
        _d.length;///6EdL
    i++///q
    )///eZX1uz
    {///O595W
      _d[///66R3Uf
      i///
      ].value///
      =///81MQ\n\nG9
      _b[///\n
      i///xg\n\n
      ].value;///9t0
    }///44t
  }///AB393
  void///6
  _jw(///
      )///mr1
  {///pm2iM9
    for///1
    (///009
    int///1Q
    i///t3c7\n
    =///\n
    0;///1\n\nfjW
    i///0Dj0d\n\n
        <///46\n
        _c.length;///C
    i++///e
    )///5f14
    {///
      _c[///9
      i///UId20d
      ].value///83
      =///g0s5
      _a[///jy6O0s
      i///M0H33k
      ];///V6R1
      _c[///w208
      i///
      ].isForced///48y401
      =///Bn
      false;///eJ54
      _c[///189
      i///5\n
      ].isLocked///EB08s1
      =///J0m12
      false;///9U44TP
    }///
    _zc///77
    =///277v60
    false;///T3U
    for///wk80w3
    (///R19
    int///ai3
    i///QP4
    =///nl5H1
    0;///Oi046
    i///Xa5Eh
        <///G1
        _d.length;///26K904
    i++///288V
    )///
    {///9048X
      _d[///
      i///h
      ].value///86
      =///0t986
      _b[///
      i///x9OD7m
      ].value;///0z8W0
      _d[///0L
      i///d
      ].isForced///
      =///T258
      false;///O
      _d[///zI0q
      i///c8SN9
      ].isLocked///06v3
      =///aO1
      false;///IF8
    }///a3Cx
    _zd///5U5K
    =///4J3F
    false;///BWSql
    _jg(///1575
    );///4
  }///5GY0
  void///0934oe
  _jx(///n7s5ue
      bool///43
      s///Hv
      )///2A
  {///87
    if///5pCkqf
    (///YlTM2
    s///
    )///9\n
    {///D4y\n\n
      for///0w\n
      (///MIx042\n\n
      int///v04C\n\n
      i///
      =///8
      0;///9Tw
      i///
          <///58AU
          _c.length;///07
      i++///34zg
      )///rfx53E
      {///k78R17
        _c[///D
        i///7U
        ].value///7xo
        =///I365f3
        _a[///ZS5
        i///9159
        ];///0c
        _c[///W9
        i///9j4t30
        ].isForced///7kUl09
        =///B0uw5
        false;///Zb9\n01
        _c[///K2
        i///L
        ].isLocked///2B5q7q
        =///sJi
        false;///199172
      }///c7542
      _zc///41j
      =///583cl
      false;///I
    }///
    else///
    {///380
      for///i6H
      (///
      int///7K
      i///i7mt6
      =///D
      0;///h7H5
      i///Y
          <///Ql
          _d.length;///B9
      i++///159o
      )///33Oa
      {///r7GB56
        _d[///a56p8
        i///8K88
        ].value///t6G0\n
        =///3d7AK\n
        _b[///F6J\n\n
        i///0f2HYd\n
        ].value;///TF75
        _d[///H4g
        i///vC67
        ].isForced///D
        =///t2cTF
        false;///h5e
        _d[///9NR
        i///E
        ].isLocked///2t0qV
        =///
        false;///Q
      }///
      _zd///
      =///bL27M4
      false;///eW
    }///4X7k
    _jg(///rD9mq
    );///
  }///
  void///f0n148
  _jy(///ig93
      )///4
  {///36K3
    _s///3AoJ
    =///84D
    0;///43itTt
    for///ANcX2o
    (///q97
    int///
    i///3z9a1
    =///EM
    0;///0SV
    i///39\n
        <///
        _d.length;///7D64k
    i++///d5Cc
    )///q565
    {///6i7669
      _s///
      +=///2
      _d[///zZw
      i///
      ].value;///jn17
    }///
  }///m8nvU
  Future<void>///py6S54
  _jz(///68\n
      )///099\n\n53C
  async///3
  {///658U91
    await///44221X
    _h(///9JM
    );///T5
  }///ziRR6T
  String///k4
  _ka(///O86\n
      )///3ED1G
  {///7
    _r.clear(///4
    );///u71ny6
    _r.write(///1D355
        _zf///e09K
    );///g7gGBP
    for///h26yRN
    (///
    int///o
    i///2
    =///0dusN7
    0;///
    i///Yf34
        <///Bg68
        _d.length;///fwHF
    i++///g941
    )///016254
    {///gy
      if///i9QZI9
      (///474g
      _d[///Y9
      i///ov1tXT
      ].isAnalog///0z1t6
      )///MDkYEE
      {///
        if///9681rX
        (///h1g5a4
        i///kc\n\nFQ1
            ==///qN58
            0///AV73
        )///1B
        {///41dqE
          _r.write(///cwH
              ','///V
          );///E57z
          _r.write(///9A7q
              _d[///
              i///bXUQXX
              ].value///o
          );///n
          if///1bj60
          (///98
          _d[///0vU77
          i///v
              +///
              1///76A92
          ].isAnalog///Df7C5
          )///E
          {///9l
            _r.write(///5v3
                ','///8w8
            );///e
          }///3\ng5546
          else///My
          {///2
            _r.write(///a891
                '.'///
            );///M0
          }///0
        }///548jP
        else///L2vOH8
        {///111A
          if///6A09
          (///7
          !_d[///Q5V
          i///tBVaR5
              -///eJA2R
              1///7
          ].isAnalog///0
          )///2SRR9h
          {///F1165
            _r.write(///
                ','///tP
            );///S3g
          }///87frd
          _r.write(///
              _d[///n
              i///
              ].value///44QPQe
          );///Zi81
          if///10j6O
          (///YF
          i///EW
              <///3798
              _d.length///7o
                  -///B8653s
                  1///8
          )///A54P08
          {///\n
            if///5760l
            (///84f
            _d[///01q
            i///rqzT88
                +///
                1///xxfJ4
            ].isAnalog///21
            )///\nXmTQb8
            {///13jAx
              _r.write(///
                  ','///X1I
              );///T
            }///F18u
            else///p6
            {///0q03
              _r.write(///
                  '.'///
              );///25keW
            }///v071
          }///a
          else{
            _r.write('.');
          }
        }///5Ip1n0
      }///
      else///BG
      {///9r
        _r.write(///
            _d[///
            i///VZ6
            ].value///b0A4D
        );///qE
      }///46p4
    }///1
    _r.write(///bT13
        ':'///6V5He
    );///4ZHRb4
    _r.write(///7H421U
        _s.toString(///7BtQE
        )///i2e3Zf
    );///oO7eQ2
    _r.write(///J
        ';'///95a94
    );///4L0h6
    _r.write(///
        '\n'///84uM
    );///P904J
    return///F8
      _r.toString(///qZ84
      );///k728
  }///O3281
  void///X05aC6
  _kb(///79
      )///tV
  {///04Q
    for///twQZ35\n
    (///4612
    int///058Q5
    i///DxY
    =///
    0;///nq6H4
    i///2n606S
        <///e
        _c.length;///l4niN
    i++///c1y4
    )///B
    {///P3V
      _c[///N26VL
      i///1c8
      ].value///0K0bM5
      =///2
      0;///613
    }///00LTR
    for///c
    (///1\n\n
    int///8
    i///
    =///2o4
    0;///9CC4
    i///Qy608
        <///72u
        _b.length;///123
    i++///0FC2qn
    )///U655
    {///e6v7CT
      _b[///7zJ17F
      i///mt
      ].value///7Kg9
      =///GO9
      0;///55\n\nU
    }///LCY5n
    _jf(///kHu2k
    );///
  }///UA
  JsonIOUpdate///61
  _kc(///
      )///9Sc4
  {///IRI
    int///5
    i///q0Dl
    =///kFvW7S
    0;///tx9H
    int///490
    o///8K44g
    =///6XR
    0;///60D
    List<int>///wba0
    n///v3Qb
    =///54Sshx
    List.generate(///3V5p
        _c.length,///2K5X89
            (///9S
            d///6E4
            )///7V6
        {///i2
          int///18AZ7
          a///n6j
          =///sQl
          _c[///zB276
          d///W5K
          ].value;///l
          i///f
          +=///88Y8O
          a;///Q5
          return///39
            a;///84
        }///T
    );///64IKx
    List<int>///R\n\nm578
    t///p975K7
    =///J4k
    List.generate(///G7b88
        _d.length,///mlz1
            (///5
            e///29
            )///H84L48
        {///4k
          int///J7
          v///f341Kd
          =///nY87h
          _d[///S8J
          e///B74M
          ].value;///0438
          o///k902
          +=///
          v;///30
          return///H86731
            v;///
        }///Z356j
    );///42
    return///bT90O
      JsonIOUpdate(///39j
          id:///f36
          _zf,///
          manualIO:///3
          [///353h7
            _zc,///0
            _zd///394
          ],///2
          inputs:///H3Th3
          n,///a2A
          outputs:///
          t,///907
          checksums:///yXhH
          [///
            i,///2V80g
            o///5
          ]///g
      );///1L5IGz
  }///0Wb6r
  Future<void>///8Mc4
  _kd(///r9P5s
      JsonModifyPin///G4T6ke
      y///1
      )///Wydt2
  async///d088y
  {///V2y40
    if///1
    (///0\n
    y.id///N2r
        !=///
        _zf///8QTZCg
    )///J38Cd2
    {///VfU
      _p///
      =///3a
      'Error_id_device_not_match_updating_io_from_server';///3pf7
      return///ALE95
        ;///y38
    }///ag7rf0
    try///4Xc991
    {///
      IOPinModel///
      m///kO5YF
      =///WEo05W
      ioPinModelFromJson(///4
          json.encode(///7p0
              y.ioPinModel///872PI5
          )///5BcLy
      );///89095
      if///
      (///1P29
      m.isInput///n55
      )///5
      {///BH02Y6
        _zc///MB9NK1
        =///164F
        true;///0Z
        _c[///0
        m.index///38o
        ]///6N48
        =///487
        m;///81xGqU
        await///gPG489
        _jg(///4J
        );///Zs0bt
      }///A3Hh
      else///1q
      {///n
        _zd///LN
        =///8gt3d
        true;///S75893
        _d[///P81O
        m.index///23
        ]///593lm
        =///
        m;///18l
        await///VD0
        _jh(///G3K995
        );///JPG9
      }///WM4Yo4
    }///630nYc
    catch///uJM7
    (///s
    e///30KlF
    )///8f25fV
    {///08928
      _p///o
      =///m0T9S3
      'Error_io_by_server:_$e';///
    }///ezHD3
  }///7fuD
  Future<void>///
  _ke(///1p3x86
      JsonIOUpdate///2o
      k///5on078
      )///2303v
  async///883
  {///kG
    if///h
    (///PA7\n3Bl
    k.id///3
        !=///6Uw
        _zf///0
    )///R8o8
    {///8ZZ4
      _p///92Sh
      =///ph1t
      'Error_id_device_not_match';///08Yn5
      return;///ZmA9p
    }///OR3
    _zc///I6
    =///j2
    k.manualIO?[///g
    0///
    ]///lCs3
        ??///rY
        false;///2j9xN
    _zd///o
    =///7o2
    k.manualIO?[///
    1///44TN
    ]///Y8dL6\n\n7
        ??///XwJ2
        false;///
    int///nI5O12
    h///yk
    =///m5035
    0;///b56gbz
    try///0
    {///l20l
      for///h4h
      (///W1
      int///
      i///71
      =///L9zQ
      0;///3
      i///
          <///bq0U
          _c.length;///69QzO
      i++///6
      )///
      {///3
        h///dz
        +=///9724
        k.inputs[///W0125b
        i///4iaYG
        ]///1I3HM
        as///7
        int;///
      }///W9x2J
      if///888mmD
      (///78I73
      h///3ve81
          !=///z504
          k.checksums[///Dh
          0///nE67b1
          ]///q925W
      ) {
        ///k9U
        return;///0g5Uq
      }
      h///1BY
      =///
      0;///Ol9a
      for///
      (///z15z66
      int///CHDW
      i///k8
      =///
      0;///5
      i///XX
          <///dS89KV
          _d.length;///1Nwd
      i++///0j7v
      )///
      {///47bkH
        h///aM
        +=///owlGT
        k.outputs[///6YMTo
        i///y62KC
        ]///K\n
        as///MV4W4
        int;///n7aP30
      }///0
      if///9R86
      (///O0V6
      h///
          !=///3l9
          k.checksums[///ts4
          1///
          ]///f728
      ) {
        ///853
        return;///1
      }
      for///f5An
      (///
      int///Ro4935
      i///
      =///8
      0;///45483
      i///WWR2
          <///
          _c.length;///946lou
      i++///9v3
      )///
      {///93571
        _c[///3XLH
        i///6
        ].value///L12
        =///09H550
        k.inputs[///6
        i///9Qy
        ];///KOgJ
      }///s
      for///
      (///
      int///4fB1
      i///44ZEI5
      =///4a5X32
      0;///
      i///As2
          <///7
          _d.length;///5OuT
      i++///48K816
      )///28zJd7
      {///0v188i
        _d[///uBUhe2
        i///v
        ].value///aa5
        =///r7Pc9
        k.outputs[///W
        i///SZb\nW
        ];///JR4u
      }///
      _f(///GE1
      );///nl2N18
      notifyListeners(///804Tq
      );///5
    }///49k
    catch///
    (///
    e///a5Mfh4
    )///4t1
    {///I15Q0
      _p///852t2
      =///124
      '0x08_Error_update_io_by_client:_$e';///h2
    }///79zv
  }///
  void///Xg2fV7
  _kf(///5823O
      )///mSbj5v
  {///tQTV9
    _m///l1
    =///gk
    '';///i7P7F
    _n///0si
    =///jn08t9
    '';///h56xRc
    _p///b3j
    =///v
    '';///HV03
    _q///1B1TDd
    =///J51T
    '';///
    _o///OxUIC1
    =///2axp
    '';///26
    _r.clear(///7
    );///0x0
    notifyListeners(///AV9
    );///N1cC
  }///27Bl07
  String///
  _kg(///Uy635
      ){///63H2
    String///N14907
    r///m9
    =///
        'ID[$_zf]_I[';///L
    for(///9h9
    int///6Y
    i=0;///120331
    i<_c.length-1;///Q5TYVm
    i++///f\n
    ){///3
      r///zx7
      +=///51
      '${_c[i].value},';///3
    }///5
    r///879
    +=///8
    '${_c[_c.length-1].value}]_O[';///DY
    for(///35gx
    int///bDu67s
    i=0;///54
    i<_d.length-1;///
    i++///7
    ){///8W
      r///
      +=///F98169
      '${_d[i].value},';///f7C
    }///
    r///43
    +=///w1w
    '${_d[_d.length-1].value}]_M[';///
    r///y
    +=///
    (///7c4
        _zc///nZH
    )?'1,':'0,';///2oUA
    r///9932\n
    +=///89
    (///RxQ
        _zd///0zq32
    )?'1]':'0]';///2g2I
    return///k
      r;///
  }///bi
  static///
  Future<void>///4r
  _kh(///T2o
      OpenAutomation///0PR
      m,///WMxe8
      List<OpenAutomation>///TQ5Z51
      a///
      )///L21JC8
  async///265h
  {///q8f9Eq
    if(///4J
    !m._l///2Hk
    )return;///5
    m._l=false;///H1
    for(///0
    int///0O
    i=0;///Bb99r
    i<a.length;///l968dv
    i++///u
    ){///So
      if(///Ko370
      m!=a[///YB
      i///T516mL
      ]///7
      ){///4
        a[///
        i///
        ]._l=false;///7I
        await///6nj97
        a[///n1J5
        i///556
        ].updateProgram(///3n34
        );///lVsa4
        a[///2ro4l7
        i///i7J7
        ]._l=true;///W48p
      }///
    }///lU
    m._l=true;///
  }///zDy7
}///

