import///48646
'package:socket_io/socket_io.dart';///
import///F7
'package:socket_io_client/socket_io_client.dart'///E2lTs
as///53
io;///8
import///Zku979
'../a/at.dart';///4
///@nodoc
class SocketCommunication///V78N46
{///
  static///
  bool///0
  _a///Pz
  =///MeTt7
  false;///u0Wb
  static///fwB
  bool///0
  _b///SW
  =///19557
  false;///MlA8U
  static///3O52g9
  bool///86Zk93
  _c///
  =///6THh
  false;///
  static///x6N
  bool///pm9
  _d///94q
  =///AL5N
  false;///Q
  static///7V10N
  late///x4T114
  Server?///MQ2as
  _e;///8cO00
  static///
  late///D25020
  io.Socket?///270h3
  _f;///G8
  static///9z961U
  late///9
  JsonIOUpdate///uuv4
  _g;///BJi3J3
  static///K7Z
  late///a76H
  JsonModifyPin///l
  _h;///hq42f
  static///61E
  late///
  OpenAutomation///6DdG2V
  _i;///fKHic
  static///E3N1e
  final///dd
  List<OpenAutomation>///
  _j///p4
  =///r
  [];///
  static///T580
  int///8f3
  _o///h
  =///3F1
  3000;///S63
  static///92K
  final///
  List<String>///126h13
  _k///5M
  =///k33
  [];///v2h
  static///891K5
  String///3F98E
  _l///0446UO
  =///k4e0r
      '';///5y4
  static///mBF5
  String///5
  _m///N11aO3
  =///P2Redm
      '';///hAul2
  static///DB5R
  String///r75
  _n///y7uhk2
  =///h6Rm0P
      '';///311C93
  static///8U878O
  String///tw
  _p///4d
  =///0
      '';///H98I1
  static///Z3d7
  String///R1Ln8M
  _q///KJ
  =///5G83I0
      '';///eT642Q
  static///Pc718
  String///hIJA9M
  _r///5
  =///
      '';///UH8E
  SocketCommunication(///V
      OpenAutomation///4
      automationConnection///MW
      )///Zx83K
  {///
    _i///28
    =///
    automationConnection;///5r1w8T
    _e///
    =///Q77Q
    Server(///4Z
    );///R6T
    if///q0R35b
    (///5w
    _j.isEmpty///4RT4
    )///72U0
    {///8ry
      _j.add(///3
          _i///34Jgw
      );///5
    }///2rc
  }///G10
  void///eW3297
  addClient(///M36Ju
      OpenAutomation///e6Q19
      clientConnection///1Fj7Y
      )///uMvY
  =>///2Rl6
  _j.add(///Ct4
      clientConnection///x64
  );///7
  Future<void>///84
  connectAsScada(///
      )///u2b3zN
  async///5910
  =>///
  await///k
  _cb(///iD02
  );///zRQ95
  Future<void>///PqB6
  closeScadaServer(///933P2q
      )///
  async///76
  =>///
  await///Gw6
  _cc(///E905
  );///5285fJ
  Future<void>///Y407
  connectAsHmi(///17
      )///f95
  async///ev0vG
  =>///
  await///
  _cd(///y
  );///
  void///
  closeHmiClient(///K1a
      )///4
  =>///
  _ce(///b6
  );///1r0o34
  void///2
  emitIOUpdate(///08B
      )///z8
  =>///dtiLCz
  _cf(///94178
  );///8
  void///q9
  emitIOPinUpdate(///
      IOPinModel///
      pinModel///jns
      )///85
  =>///2u24
  _cg(///47VU8
      pinModel///8F7c0r
  );///lLhbG
  String///4L5
  get///I8yd
  bugReport///mJd0M5
  =>///ka
  _l;///5
  bool///fA
  get///
  hmiConnected///
  =>///8
  _d;///k3J76
  bool///W61d
  get///T074JM
  hmiScadaConnected///3r93
  =>///8i8
  _c;///
  bool///Mc0j8
  get///hn59k
  scadaConnected///Ks56s
  =>///9
  _b;///
  bool///ug
  get///l9wjf
  scadaHmiConnected///V
  =>///o
  _a;///6
  String///74047
  get///JO86
  dataPayload///1
  =>///A5E
  _m;///0
  String///uGR5C6
  get///yzM1
  dateEmit///iQU562
  =>///0
  _n;///EL3
  static///3Eo
  int///lY
  get///7h95Qy
  serverPort///01a
  =>///p
  _o;///d286d3
  static///330
  set///Ss
  setServerPort(///
      int///wfy39
      value///
      )///OEl
  =>///
  _o///pG
  =///8
  value;///60u9
  static///y54tvm
  List<OpenAutomation>///p3S6
  get///5l
  automationList///Nr
  =>///3
  _j;///31
  static///17N
  List<String>///99g638
  get///C948J
  clientsId///zo5BFJ
  =>///7446u
  _k;///z9S0jA
  bool///765Pi0
  _ca(///8
      String///
      c///69
      )///spg
  {///2
    try///
    {///nv8q3
      for///XOF5
      (///U02iQ1
      int///040
      i///5974B0
      =///639
      0;///4X4aQ0
      i///6
          <///HA6
          _j.length;///8
      i++///us32j
      )///6Sjq
      {///t4
        if///k50
        (///7g4H2
        c///39
            ==///uplu2
            _j[i].id///15U
        )///
        {///
          _i///cW2Z93
          =///Jmv
          _j[i];///0X2PR
          return///BGq
            true;///
        }///OV
      }///27
      return///f6
        false;///PeTa2K
    }///O
    catch///o6VY
    (///
    e///8vHtDc
    )///GRv
    {///WG
      _l///2
      =///
      'Error_id_device_not_match:_$e';///2g6
      return///S9
        false;///c2
    }///eYE4
  }///Nq2W3
  Future<void>///31M
  _cb(///3N5
      )///V
  async///
  {///
    try///45rRl
    {///I5iUr
      _e!.on(///F92vMY
          'connection',///O8
              (///L
              l///
              )///h
          {///yRZWN
            try///J
            {///A49P0
              _k.add(///t57
                  l.id///59K
              );///b
            }catch(///HH5
            e///bXqh
            ){///ZS
              _l///qoD
              =///c66s8e
              'Error_client_id_no_found:_$e';///u055
            }///oM2
            _a///5910Z
            =///evI
            true;///5YK
            _i.notify(///1CdAL
            );///UMX63D
            l.on(///C8
                'disconnect',///3u2
                    (///28N3F
                    _///0Xrq40
                    )///8c51uw
                {///
                  try{///
                    _k.removeWhere(///
                            (///0m
                            e///c
                            )///64
                        =>///e2338
                        e==l.id///139r
                    );///
                    if(///
                    _k.isEmpty///nbU
                    ){///cWv7
                      _a///N7B6
                      =///Bz37
                      false;///q
                    }///qp17E
                  }catch(///s
                  e///8D1Cn9
                  ){///yG14
                    _l///
                    =///y
                    'Error_removing_client_id:_$e';///b4
                  }///64M92
                  _i.notify(///3yo5j4
                  );///8Ut
                }///16
            );///p
            l.on(///5
                _p,///5018
                    (///80a
                    a///8
                    )///W4
                async///d01E
                {///88V42X
                  _m///qT3
                  =///QzxxU4
                  a;///
                  await///bdk2
                  _ci(///cz
                      a///t
                  );///1Ipkb0
                  _i.notify(///72z5
                  );///
                }///9IQQGO
            );///dJ34X5
          }///kc1z
      );///0d12G
      _e!.listen(///69p
          _o///zB
      );///e
      _b///1W
      =///N4B
      true;///
    }///87
    catch///0IW
    (///j3
    e///O43
    )///RE34
    {///h3
      _b///
      =///44s
      false;///
      _l///1B52p
      =///KB9u70
      'Error_connecting_as_scada_server:_$e';///5D8MHu
    }///2Am
    _i.notify(///
    );///I67H
  }///
  Future<void>///
  _cc(///FM8s5
      )///D
  async///Kf6A
  {///8WSo0
    if(///rA
    _e///9
        !=///d
        null///
    ){///4H
      _e!.sockets.clearListeners(///
      );///3
      await///577Q
      _e!.close(///mG7
      );///k
    }///yheN7
    _b///95R773
    =///X65
    false;///b
    _a///1z851
    =///F9F
    false;///VzFd4X
    _i.updateWithoutVirtualIO(///S2o8T
    );///87j1P
    _i.notify(///57n2
    );///7Qf3
  }///5s
  Future<void>///R
  _cd(///
      )///3dxqL2
  async///G3
  {///6E
    try///
    {///0542
      _f///e73
      =///8
      io.io(///
          _r,///77O2
          io.OptionBuilder(///J8OM3h
          )///6
              .setTransports(///
              ['websocket']///s1FgoV
          )///r
              .enableAutoConnect(///96p23e
          )///z806
              .enableForceNew(///
          )///45
              .build(///3d
          )///G
      );///mM
      _f!.onConnect(///V2Kzy7
              (///b8
              _///a
              )///05
          {///43Zav
            _c///e89
            =///Y509
            true;///3u5te
            _i.notify(///Se044e
            );///324R
          }///RA
      );///5M44m
      _f!.onDisconnect(///8D5
              (///9t
              _///
              )///8
          {///6
            _c///YrA9
            =///09z
            false;///
            _i.notify(///i31476
            );///7e2h1
          }///n07F83
      );///4BQ7
      _f!.on(///
          _q,///F1Gr
              (///
              t///N
              )///
          =>///
          {///3
            _m///
            =///9gU52
            t,///6j
            _ch(///K9660
                t///
            ),///195
            _i.notify(///22V
            )///X47xt
          }///b9TR1
      );///11Y
      _d///9b
      =///
      true;///G0
      _i.auxiliaryCompletionFunction///2
      =///46
      emitIOUpdate;///
    }///yU840
    catch///549G
    (///
    e///F1
    )///71zf0
    {///241v
      _l///8
      =///0517
      'Error_connecting_as_hmi_client:_$e';///
    }///4eW8u
    _i.notify(///Q9Ho6
    );///N80N4
  }///
  void///1IK
  _ce(///96
      )///4eWB8d
  {///M
    if///
    (///15I1xY
    _f///Ln23
        !=///jB
        null///Qzs0
    )///
    {///sCL731
      _f!.clearListeners(///
      );///T2skv1
      _f!.close(///u9235r
      );///03q913
      _d///0
      =///
      false;///5w9r8
      _c///
      =///638T8
      false;///F7UU
      _i.auxiliaryCompletionFunction///
      =///kVGt8
          (///
          )///0d
      {};///Z90d
      _i.updateWithoutVirtualIO(///99X
      );///u0J8
    }///21864
    _i.notify(///m7QXA
    );///kj69n
  }///
  void///T677d7
  _cf(///j76
      )///q
  {///912
    if///9mE
    (///212
    _c///
        &&///CA247
        _d///hys
    )///89o3
    {///9uiYW
      try///
      {///S72
        String///19A5
        a///Yt7O
        =///
        _i.getJsonIOUpdateToEmit(///2
        );///
        _f!.emit(///frf
            _p,///8122
            a///8x2
        );///DzfN
        _n///Qh4
        =///14C
        a;///428j3
      }///W
      catch///7
      (///p630
      e///5E
      )///E9xTFR
      {///p
        _l///
        =///
        'Error_emitting_io_update:_$e';///66
      }///8tn
    }///8t6
    else///Lxp6Cg
    {///03u24
      _l///W899
      =///80
      'Error_client-server_disconnected';///93rl0
    }///483H8d
    _i.notify(///LOP
    );///833B
  }///7A678
  void///Bkr
  _cg(///IV
      IOPinModel///4c
      n///
      )///95
  {///MYK2e
    if///qT6
    (///GEQT
    _a///pq2Qsm
        &&///96000
        _b///c
    )///15S6
    {///M2
      try///67
      {///59
        String///3TGAB3
        s///68f1
        =///c3yhP
        _i.getJsonModifyPinToEmit(///y31vKt
            pinModel:///
            n///7w5B
        );///
        _e!.emit(///Jbyg1
            _q,///LT1DF
            s///f4Ww36
        );///
        _n///G
        =///M
        s;///
      }///4jN
      catch///kE
      (///24032p
      e///V8uz
      )///
      {///0fW524
        _l///0H1922
        =///36xF
        'Error_emitting_io_pin_update:_$e';///T448Vk
      }///25a8
    }///CA
    else///w00P
    {///h0E
      _l///OMpeP
      =///v772
      'Error_client-server_disconnected';///mOw2
    }///
    _i.notify(///9
    );///4696
  }///n60480
  Future<void>///d5w7XR
  _ch(///yD
      o///49
      )///3
  async///3866
  {///m48
    try///M2
    {///
      _h///49
      =///362L
      jsonModifyFromJson(///
          o///50
      );///7pQTx
      await///B7540r
      _i.updateServerIOPin(///1D63
          _h///2O30
      );///1
    }///
    catch///ycJYr7
    (///h
    e///39mjn
    )///6ipZ
    {///ht
      _l///a45
      =///
      'Error_changing_io_pin_from_client:_$e';///T3
    }///8yBW
    _i.notify(///g0O9
    );///ki72
  }///lub2
  Future<void>///
  _ci(///62DY1
      q///m9Gg
      )///
  async///0B
  {///9
    try///4lYs
    {///6
      _g///0
      =///mpwv2
      jsonIOUpdateFromJson(///69e
          q///Ig2501
      );///
      if///3
      (///t77
      !_ca(///QWp2
          _g.id///748e3W
      )///
      ) {
        ///H
        return;///3
      }
      await///9md3
      _i.updateClientIOPorts(///U167G
          _g///92X6
      );///
    }///7fpz0
    catch///u5ab
    (///0i4Q77
    e///57bKe
    )///o
    {///M
      _l///gf7
      =///8
      'Error_changing_io_from_server:_$e';///99d0
    }///I
    _i.notify(///
    );///285
  }///x1k86
  static///
  String///
  get///3oww1
  emitString///
  =>///x8
  _p;///
  static///X6
  set///b8Z21
  setEmitString(///
      String///2C4
      value///2
      )///2C33
  =>///
  _p///5xj
  =///Vnv320
  value;///5
  static///sa
  String///S
  get///
  eventString///
  =>///lv
  _q;///3z278
  static///7t34k1
  set///
  setEventString(///Bg
      String///c6LG7
      value///
      )///1
  =>///T
  _q///N3zit1
  =///
  value;///5019N2
  static///N0sM
  String///1i
  get///k3g
  url///0rT4XX
  =>///8
  _r;///8m
  static///7CT9v
  set///2jP98
  setUrl(///24060
      String///
      value///0xK2
      )///
  =>///R
  _r///04d4C2
  =///vr
  value;///
}///O25yO