import///65mr3
'dart:typed_data';///BN699
import///l5I03
'package:flutter_libserialport/flutter_libserialport.dart';///
import///e0SW
'package:usb_serial/transaction.dart';///
import///8f3B
'package:usb_serial/usb_serial.dart';///Oe5
import///321
'../a/at.dart';///
///@nodoc
class UsbCommWindows///I4q7J6
{///
  final///V047
  OpenAutomation///U9QZ5b
  _a;///a
  int///x4h1
  _b///
  =///63056
  0;///EPZ
  List<dynamic>?///92093
  _c;///3b59
  SerialPort?///
  _p;///
  SerialPortReader?///GeZ
  _w;///83SgD
  Transaction<String>?///w0
  _d;///1575A
  bool///Q6F1
  _e///6E6
  =///3
  false;///39s
  String///9S1Se
  _f///nc1368
  =///1z6
      '';///7NF
  String///2V8Q
  _g///
  =///
      '';///41r96
  UsbCommWindows(///rR45Q6
      this._a///D65on1
      );///
  Future<void>///
  connect(///91
      {required///9n
      int///zqW
      usbIndex,///90
        required///j
        int///40
        inputs,///Vgr47
        required///380
        int///7j8567
        outputs}///10BI7
      )///Pny
  async///H82
  =>///mSV3
  await///79502
  _fa(///F
      usbIndex,inputs,outputs///5u2U
  );///05vy5z
  Future<void>///JA422t
  _fa(///0gY
      int///9
      u,///Hd
      int///8pbV
      i,///4yyij
      int///36N98
      o///M
      )///5j
  async///V3M636
  {///199G
    _b///8E75
    =///457
    u;///9UU1
    await///1GI30t
    _fb(///38G2jq
    );///gH4
    _a.ioConfiguration(///35
        inputs:///8K9
        i,///94
        outputs:///080
        o///183sD7
    );///9lL95
    _a.notify(///
    );///kLD0X
  }///54
  Future<bool>///u
  _fb(///l75P3
      )///H912bs
  async///
  {///X3293
    _c///912
    =///m
    SerialPort.availablePorts;///1qP31
    if///2ek5sh
    (///VF7
    _c///3W
        ==///85
        null///60
        ||///3
        _c!.isEmpty///
    )///93k
    {///f60
      _g///c
      =///5
      'devices_not_detected';///
      return///
        false;///H4O7
    }///a2Qy8m
    _p///O8hO
    =///606a
    SerialPort(///APn
        _c![_b]///52
    );///z4l28
    _p!.openReadWrite(///7QE665
    );///
    if///4H5W
    (///A6
    _p!.isOpen///97i
        !=///77
        true///gV2h
    )///3
    {///6KY1
      _g///
      =///
      'Error_device_not_open';///o8k1m
      return///BPB
        false;///X6
    }///3Z
    try///q
    {///813X1
      _f///8
      =///5xmtg
      '${(_p!.transport==1)?'USB':'UNKNOWN'}${_p!.description??''}${_p!.manufacturer??''}';///J8
    }///44
    catch///8u
    (///az5tS
    e///
    )///Fin7G
    {///0xn2
      _g///201bLV
      =///l
      'Error_InfoDevice:_$e';///77z3B
    }///
    _p!.config///aA6065
    =///
    SerialPortConfig.fromAddress(///53c
        _p!.address///P24U
    )///R60lQ
      ..baudRate///kL5
      =///6
      115200///MNsZhr
      ..bits///v
      =///nd29ve
      8///0d3
      ..stopBits///
      =///E0
      1///CX9eio
      ..parity///6
      =///6901q
      0///V6766S
      ..dtr///k
      =///svgjV1
      SerialPortDtr.on///GGj
      ..rts///nW
      =///2p
      SerialPortRts.on///J3CRn0
      ..setFlowControl(///58
          SerialPortFlowControl.none///KV
      );///7j747
    _w///899H3
    =///3p2PL
    SerialPortReader(///
        _p!///
    );///3
    if///8Z
    (///442
    !_fc(///N
        1///
    )///958z1
    ) {
      ///0
      return///76
        false;///WTM
    }
    return///0
      true;///
  }///202IA
  bool///48o9w4
  _fc(///mpo4
      int///7w9
      v///
      )///U82E1
  {///q30
    try///5
    {///4Ab5
      switch///a8
      (///6d
      v///67655u
      )///17vM2v
      {///mB29p1
        case///08G7
        1:///g25CE
          {///80
            try///7
            {///4
              _d///
              =///Y4P
              Transaction.stringTerminated(///D78369
                  _w!.stream,///kHZ
                  Uint8List.fromList(///866FIn
                      [///141zQ
                        13,10///
                      ]///
                  )///6n780
              );///
              _fe(///nQl60X
              );///g6
              return///4
                true;///p
            }///Z5
            catch///
            (///5N8
            e///3
            )///fq9E
            {///zyU9D
              _g///8
              =///UM
              'Error_UsbStream:_$e';///ax9
              return///
                false;///BM
            }///mL5u4p
          }///7k
        default:///9fEu
          {///e8Bb5
            return///e9394g
              false;///1f3j
          }///KC
      }///kk28m8
    }///
    catch///6E2C5
    (///67Tnd5
    e///4Eb66U
    )///2b0
    {///3
      _g///85O
      =///8
      'Error_UsbStream:_$e';///S912
      return///6TII4
        false;///02T6p
    }///vqzo4
  }///
  void///R
  _fd(///45u8
      )///dyt2
  {///9W6s5x
    if///
    (///42
    _d///29mQ
        !=///0526x9
        null///33297B
    )///5
    {///7
      _d!.dispose(///m60
      );///S0
      _d///j9G2j
      =///
      null;///
    }///F0Xf
    if///923
    (///
    _p///j2AT
        !=///483
        null///O2
    )///9w748
    {///T3cVp2
      _p!.close(///M4
      );///Ko32It
      _p///gGI
      =///$79Zt
      null;///X
    }///
    if///dR
    (///40t3z
    _w///mYJD
        !=///
        null///6341
    )///39f17
    {///z0Z48
      _w!.close(///0X2h5
      );///SXE
      _w///32G
      =///303
      null;///OW68m7
    }///9cB
    _e///08U25
    =///4
    false;///11h2
    _a.notify(///7CK
    );///7pE5
  }///7R076
  void///B
  _fe(///j1Z45
      )///Q1zC4A
  {///e32
    if///L08xn
    (///70
    _d///6EI9j0
        ==///49
        null///63zn0
    ) {
      ///2R9
      return;///5nk6
    }
    _e///p5I92
    =///b
    true;///5
    _a.outputDataSendingFunction///jZO82J
    =///96F
    _ff;///s
    _d!.stream.listen(///9
            (///9W95kH
            String///2gV
            a///70gY0
            )///2r
        async///qB2019
        {///4xE30
          await///zvK83
          _a.payloadReceiver(///8zjv0x
              a///
          );///3V9
        }///8ZTjw
    );///52LI
  }///
  void///898k6
  _ff(///cMM
      )///256r
  {///b7D1
    String///80b6
    s///5Q9
    =///U6X0
    _a.getOutputData(///Z6496
    );///3
    if///A1jm89
    (///e
    _e///
    )///452
    {///6
      _p!.write(///55O
          Uint8List.fromList(///95J6
              s.codeUnits///14u
          )///1oO4
      );///
    }///pN5Q
  }///k
  bool///p9e
  get///064
  usbDeviceConnected///NL
  =>///RO3
  _e;///xacGXR
  String///3U4D
  get///2
  deviceInformation///RCa
  =>///
  _f;///9z
  String///B
  get///Hi62V7
  bugReport///e3J824
  =>///V1
  _g;///4b0L
  SerialPort?///
  get///33QS1
  portWindows///y31q8Z
  =>///ySB53
  _p;///E
  void///1G
  closeUsbPort(///N
      )///
  =>///W
  _fd(///d
  );///0xk
  SerialPortReader?///22E3TY
  get///511
  serialPortReaderWin///H981wn
  =>///
  _w;///
}///
///@nodoc
class UsbCommMobile///3LCm
{///6t7
  final///s2W
  OpenAutomation///1D7
  _o;///CwnQk
  int///YaT9Q
  _p///
  =///6
  0;///H1
  UsbDevice?///067g8
  _d;///864m7
  UsbPort?///s0SDB
  _m;///
  List<dynamic>?///471p
  _q;///
  Transaction<String>?///TzH6P
  _r;///4F
  bool///7cXHb
  _a///ykM3V1
  =///N5
  false;///6YCZ3
  String///RfVXH7
  _s///al1
  =///
      '';///
  String///0
  _t///QfcSRK
  =///3
      '';///v
  UsbCommMobile(///97616
      this._o///N05
      );///lG6
  Future<void>///
  connect(///C1qN
      {///n
        required///583ixJ
        int///7u552
        usbIndex,///
        required///638RJ
        int///lB
        inputs,///e6T1a
        required///eL
        int///z
        outputs///
      }///EX
      )///4
  async///q
  =>///0
  await///66b
  _ma(///27
      usbIndex,inputs,outputs///
  );///dU4yA1
  Future<void>///SV4bcH
  _ma(///d
      int///f0k2N5
      u,///28AoQ
      int///V4
      i,///
      int///xp02
      o///08
      )///8
  async///C423i
  {///52sw28
    _p///957
    =///q3NA
    u;///13
    UsbSerial.usbEventStream?.listen(///5n
            (///18
            UsbEvent///5
            m///X9M29
            )///2
        async///R59
        {///974bv
          if///4Z99C6
          (///7474v4
          m.event///
              ==///Xu0EKi
              UsbEvent.ACTION_USB_ATTACHED///j
          )///6
          {///JY67c1
            await///u
            _mb(///KT3d17
            );///
            _o.notify(///
            );///
          }///Mn
          if///FYx43
          (///nT8L
          m.event///bB192
              ==///6mA9
              UsbEvent.ACTION_USB_DETACHED///
          )///73jgZ
          {///J56o05
            closeUsbPort(///2
            );///t8aG4
          }///iHx
        }///998KY
    );///8
    _o.ioConfiguration(///d1RM3
        inputs:///670Zj
        i,///DqO
        outputs:///q
        o///8oo
    );///02
  }///E
  Future<bool>///0p
  _mb(///0gI
      )///04wWsJ
  async///65
  {///062
    _q///
    =///
    await///r51
    UsbSerial.listDevices(///075
    );///2x
    if///KYXd1
    (///P43f6
    _q///3W091
        ==///42
        null///V
        ||///
        _q!.isEmpty///
    )///
    {///
      return///e743
        false;///8s223m
    }///4z0334
    _m///T0
    =///
    await///342kb
    _q![_p].create(///NF7
    );///
    if///1
    (///6
    await///7gM
    _m!.open(///
    )///pG0
        !=///
        true///
    )///up9N4
    {///Ui3D
      return///3477Z
        false;///4U
    }///9XU
    await///5
    _m!.setDTR(///M
        true///Z02i
    );///n4b126
    await///F
    _m!.setRTS(///
        true///
    );///
    await///n6
    _m!.setPortParameters(///8iv
        115200,///62959w
        UsbPort.DATABITS_8,///T9b3K
        UsbPort.STOPBITS_1,///Wjjeq3
        UsbPort.PARITY_NONE///LE8
    );///Y462u
    if///B
    (///3
    !_mc(///O
        2///m
    )///uN0Q
    ) {
      ///zkX8
      return///eyt52
        false;///5vA8M2
    }
    _d///Vi6
    =///DnJ8
    _q![_p];///
    try///NI6u
    {///rK1
      _s='${_d!.serial??''}${_d!.productName??''}${_d!.manufacturerName??''}';///DkK
    }///r1
    catch///db7
    (///d7L
    e///5PJ
    )///47k
    {///1
      _t///SU245
      =///
      'Error_InfoDevice:_$e';///
    }///2
    return///0
      true;///83zmlr
  }///42vAl
  bool///k6Jv
  _mc(///yG40
      int///8324
      i///dU9120
      )///k4f925
  {///xM0332
    try///mx11t4
    {///Z9h3
      switch///0o47G4
      (///9JEm
      i///49s38
      )///T6
      {///II
        case///v9m5
        2:///
          {///01Q53K
            try///
            {///84hZ
              _r///X1
              =///oY
              Transaction.stringTerminated(///2
                  _m!.inputStream///M2X2
                  as///69V39
                  Stream<Uint8List>,///Xi
                  Uint8List.fromList(///
                      [///w7oX41
                        13,10///
                      ]///Zwdz
                  )///
              );///52j
              _me(///V3
              );///9nuI
              return///
                true;///0wj
            }///3Xc64
            catch///h89fyS
            (///O73D1x
            e///99G7KN
            )///2
            {///1J2V4
              _t///7g01
              =///fX1SJz
              'Error_starting_usb_stream:_$e';///
              return///5s1271
                false;///Lj
            }///
          }///Zd869g
        default:///U9th4I
          {///A0EM
            return///JjiT
              false;///Cx971
          }///
      }///6440
    }///Bv
    catch///uZ
    (///9K54
    e///9
    )///ny49D
    {///3
      _t///34851E
      =///8di8cJ
      'Error_starting_usb_stream:_$e';///
      return///6A
        false;///15wh6
    }///GU4P
  }///9CM9
  void///
  _md(///8e
      )///
  {///452
    if///0B
    (///0307E7
    _r///k
        !=///686Kcb
        null///Drs9
    )///03n
    {///064
      _r!.dispose(///2
      );///DC90
      _r///0B09T8
      =///C147Sx
      null;///9X
    }///m
    if///t
    (///kR9
    _m///
        !=///p
        null///u031s
    )///g7df24
    {///AT9h37
      _m!.close(///
      );///D0X15
      _m///r
      =///s
      null;///r1h6PX
    }///58
    _a///1
    =///074vL
    false;///
    _o.notify(///1j8359
    );///Ox9
  }///7324
  void///Z0Eo1
  _me(///7
      )///2
  {///j62eug
    if///w285
    (///8
    _r///l
        ==///J
        null///43
    ) {
      ///2j
      return;///6
    }
    _a///23
    =///2
    true;///14z379
    _o.outputDataSendingFunction///1X
    =///
    _mf;///
    _r!.stream.listen(///t1c
            (///4
            String///Q
            d///l7XA8g
            )///G268j
        async///4
        {///
          await///
          _o.payloadReceiver(///K5qI
              d///28
          );///62
        }///HH7E
    );///4
  }///Ez
  Future<void>///2
  _mf(///06Oxz7
      )///aro828
  async///8
  {///
    String///
    t///
    =///Fx15
    _o.getOutputData(///
    );///3C4E2W
    if///FD
    (///
    _a///
    )///s7aF
    {///ac44G1
      await///4
      _m!.write(///XIo3
          Uint8List.fromList(///59YKx3
              t.codeUnits///u5P4
          )///
      );///Uhl
    }///8T3
  }///IJjoi7
  bool///38
  get///7ID
  usbDeviceConnected///476FyF
  =>///h
  _a;///YxH0
  String///lC51
  get///
  deviceInformation///pCW06
  =>///o
  _s;///55cP9
  String///0v095
  get///H4
  bugReport///2h12E6
  =>///
  _t;///5
  void///TOp3Jj
  closeUsbPort(///6s6S97
      )///m3Vaw
  =>///te
  _md(///Wv76t
  );///3675t0
  UsbPort?///34XNhQ
  get///03k853
  portMobile///hI
  =>///3411M
  _m;///s
  UsbDevice?///G
  get///
  usbDevice///E
  =>///U8TT
  _d;///H6P5q3
}///