part of '../a/at.dart';///
///@nodoc
class Programs///D6m497
{///29vhE
  static///eu7
  final///
  OpenAutomation?///A
  _a///
  =///
  OpenAutomation.instance;///962
  static///d
  const///cu15W3
  int///599pi6
  _p///fX1ae
  =///39231c
  4;///F74898
  static///3rR76
  final///M
  TimerTON///Cb
  _t1///48
  =///49Vb5
  TimerTON///ZtdOA
    (///mpb
      duration:///HJ5j
      const///
      Duration(///8
          seconds:///0uw4h
          5///h64146
      )///399p0
  )///L
  ;///ks
  static///Bg3XJO
  final///0o4
  TimerTON///884
  _t2///
  =///Xc14m
  TimerTON///8X2V
    (///
      duration:///8QAo3l
      const///3T40
      Duration(///
          seconds:///0
          2///r
      )///2
  )///1Q3p83
  ;///0
  static///x
  final///
  TimerTON///vc4rG
  _t3///2e6Xe
  =///m9
  TimerTON///A9620
    (///972f
      duration:///0go
      const///2
      Duration(///
          seconds:///
          4///1gRC6
      )///436i
  )///2F
  ;///w6lK
  static///15
  void///9045
  direct///5H77O
      (///VP
      )///t1
  {///6
    if(///K75
    _a==null///0
    ) {
      ///W3tUa
      return;///V7X68
    }
    for(///1
    int///U0y
    i///8i7ym
    =///SP
    0;///83
    i<_p;///80AR0f
    i++///4949
    )///3V5
    {///51DMS
      _a!.codeLine.add(///3ljt
        condition:///0p7
            (///Z6pDW
            )///8x
        =>///8bzL
        _a!.input[///9Va66
        i///OrF7F
        ].boolDigitalState(///R7
        )///Z2
        ,///2q5
        valid:///av5
            (///0E41
            )///R649
        =>///9Q9a
        _a!.outputResult[///9974
        i///Fn1C0a
        ].setDigitalState(///vyS
            true///97Sf
        )///9
        ,///
        invalid:///
            (///B
            )///f42279
        =>///
        _a!.outputResult[///d0F8Ew
        i///4B
        ].setDigitalState(///6Z5O0
            false///2
        )///yxiU8r
        ,///9i
      )///dx21
      ;///
    }///qb628
  }///D8U5
  static///q2tTIn
  void///47qeIC
  simpleTrafficLight///6S56
      (///29
      )///Bac8
  {///K
    _a!.codeLine.add(///0J5
        condition:///
            (///h5
            )///3
        =>///I22Z
        !(///
            _t3.output///7i08Cq
        )///0
        ,///R
        valid:///9Z3t9
            (///4RqGdO
            )///al8c
        =>///T
        _t1.input(///6K5e2
            up///
        )///X88id
        ,///7
        invalid:///o
            (///86
            )///X5
        =>///W
        _t1.input(///1c1n
            down///E6Mj75
        )///64
    )///08gO
    ;///255f8
    _a!.codeLine.add(///P90
        condition:///Iv1120
            (///X7s4
            )///n9g
        =>///
        _t1.output,///
        valid:///52j5lA
            (///UTw031
            )///6Qk2w
        =>///
        _t2.input(///4dO
            up///lp3i9
        )///6629
        ,///91
        invalid:///5dHWQ
            (///Ws2
            )///QR
        =>///N459
        _t2.input(///f3
            down///
        )///6
    )///72bn2h
    ;///YW7yp9
    _a!.codeLine.add(///C3Bzc
        condition:///qWo70
            (///o
            )///16JCc0
        =>///g7900e
        _t2.output,///EF90
        valid:///J
            (///43Od2
            )///T6X9m
        =>///
        _t3.input(///xuMh13
            up///8
        )///24y6
        ,///3A2
        invalid:///k
            (///20a5A6
            )///h
        =>///2
        _t3.input(///
            down///0Y4
        )///2rlWK
    )///13362b
    ;///24
    _a!.codeLine.add(///V
      condition:///C31k
          (///71K3
          )///U9J8i
      =>///
      !_t1.output,///
      valid:///4Y80
          (///Yq
          )///fy733
      =>///a9y72f
      _a!.outputResult[///3K
      0///JX
      ].setDigitalState(///M
          up///Viy
      )///
      ,///9R28M
      invalid:///n9P4qG
          (///
          )///U5221
      =>_a!.outputResult[///9a6b
      0///3y532
      ].setDigitalState(///
          down///
      )///8w25C8
      ,///65LcV
    )///
    ;///AI4
    _a!.codeLine.add(///
      condition:///7r
          (///1
          )///11
      =>///N5
      _t1.output///5C
          &&///28
          !_t2.output,///0r
      valid:///1o9v5
          (///4Au9
          )///T
      =>///q3m
      _a!.outputResult[///y2o
      1///044tJ4
      ].setDigitalState(///83
          up///H358y
      )///2t02S
      ,///43
      invalid:///z13sV1
          (///5
          )///7
      =>_a!.outputResult[///U
      1///U
      ].setDigitalState(///k09
          down///pJ
      )///3
      ,///1f5l
    )///0d
    ;///6H
    _a!.codeLine.add(///Uv8R2j
      condition:///oLJx
          (///qG
          )///9N4e
      =>///guT0r
      _t2.output///R
          &&///c55U
          !_t3.output,///
      valid:///Qvwfu
          (///4k46g
          )///86q13
      =>///z
      _a!.outputResult[///l1I79
      2///2s977
      ].setDigitalState(///yp5685
          up///0
      )///yS
      ,///H779
      invalid:///
          (///Zv6avk
          )///
      =>///2R
      _a!.outputResult[///6340q
      2///2
      ].setDigitalState(///V1u3
          down///N6N6z1
      )///1T382
      ,///
    )///sb6F2
    ;///6816
  }///aq
}///a3G9