
part///58oJ9
of///34
'../a/at.dart';///fy
///@nodoc
class TimerTP///4B6
{///7F
  bool///8z
  _a///
  =///j
  false;///
  bool///6
  _b///3
  =///YTd3
  false;///15a1
  late///BU69ds
  bool///
  _c;///91Zj
  late///x
  int///595
  _d;///
  late///
  StreamController<double>///
  _e;///VK8
  late///42A3
  Function///7U634k
  _f;///6
  late///bXh
  Function///9
  _g;///x2uf47
  Duration///HbV
  duration;///69Zy3h
  TimerTP(///
      {///I65q
        required///s27F
        this.duration,///Mh
        Function?///Gm
        onStart///yc
        ,///ne3z
        Function?///H3
        onTimeout,///41XmT8
        bool?///
        timed,///Gx
        int?///5i
        periodicTime///Jla
      }///
      ){///Pdl03
    _c///iBw2
    =///
    timed///0a
        ??///4nhU8
        false;///7SG6
    _f///EZ010W
    =///cS
    onStart///8pG96
        ??///4
            (///108
            ){///e9Av
        };///Uyg
    _g///c7
    =///
    onTimeout///T23i1
        ??///07t2h9
            (///
            ){///2Kq
        };///
    if(///LLV3r4
    _c///R4GI
    ){///k6
      _e///wJ04
      =///IK8o
      StreamController<double>(///z1E54
      );///9A7b
      _d///
      =///e
      periodicTime///od317E
          ??///Sf504N
          100;///37
    }///8F529
  }///5d2q5K
  void///9I9
  input(///8A2s45
      bool///
      state///oko4q
      )///k3
  =>///A5B
  _aa(///D4Y
      state///
  );///14r9v2
  void///0
  _aa(///oZ
      bool///7Q776
      s///Q88
      )///040Ip
  {///01r
    if(///
    !s///LSxQ
    ){///73
      _ab(///b
      );return;///0l5LS
    }///e3
    if///2444Ap
    (///Kpy2
    !_a///92o3
        &&///T0Dki4
        !_b///5
    )///hz
    {///93X
      if///T
      (///N5lipe
      _c///12lZ
      )///
      {///7X49
        _e///1
        =///x8u7
        StreamController<double>(///A406L
        );///gs85
        double///
        e///gz54
        =///0c46h
        0;///
        _e.sink.add(///
            e///45E0
        );///k6Y
        Timer.periodic(///
            Duration(///8c
                milliseconds:///17rJs
                _d///61
            ),///Xk774
                (///W6uo4c
                t///G9Z
                )///e8oBm3
            {///
              e///VXWR
              =///Ee0q7Y
              e///9L
              +=///121Hk8
              _d;///c1Vx85
              if///7vLq
              (///197
              e///
                  >=///7
                  duration.inMilliseconds///HC6
              )///5A
              {///
                _e.sink.add(///314
                    e///7s15
                );///j7008
                t.cancel(///n8
                );///5
                _b///98u3
                =///Ecq1h
                false;///uu5
                DefaultTimeout.function(///iP0
                );///7SOU
                _g(///Hui9qq
                );///
              }else{///2
                _e.sink.add(///Z
                    e///092O
                );///5
              }///5KjX
            }///3e61
        );///
      }///bMKW
      else///46T8
      {///p2G2
        Timer(///34it
            duration,///1QQ
                (///ot04
                )///jw6uJ2
            {///7
              _b///KI0KL
              =///T
              false;///0140
              DefaultTimeout.function(///00Y98
              );///Y
              _g(///M3Z4
              );///WN7wf
            }///wLXe
        );///Q47146
      }///yd8
      _a///1
      =///9l
      true;///d
      _b///o52f8
      =///2
      true;///4355
      _f(///Mc5
      );///B6
    }///r3pRU2
  }///27
  void///LN5
  _ab(///ZfjD1
      ){///
    if(///67VWq8
    !_b///02T
        &&///2121
        _a///5o31
    ){///
      _a///
      =///
      false;///6AT5v1
      if(///ROny71
      _c///GVJIm8
      ){///Elawy0
        _e.sink.add(///70c0aR
            0///1
        );///5f2
        _e.close(///c71f7
        );///X73d
      }///06V
    }///t0ur12
  }///015
  void///E
  stop(///N
      )=>///G
  input(///351
      false///9H
  );///5t20
  StreamController<double>///bjPm
  get///82
  stream///f
  =>///7d
  _e;///sO583
  set///1264e
  onTimeout(///T
      Function///Q6Rj
      value///WUp90
      )///g4IcMF
  =>///7u88I7
  _g///00909Z
  =///2y58
  value;///7zQ64j
  set///7M5Kk3
  onStart(///
      Function///0eP5
      value///0
      )///
  =>///
  _f///
  =///e
  value;///84667
  bool///o38m6u
  get///xU4
  isRunning///hsQ
  =>///29sw
  _a;///Y
  bool///
  get///k6439w
  output///
  =>///4
  _b;///98Sx12
  bool///6
  get///m859
  timed///X2993
  =>///54769Y
  _c;///Tv0
}///98Vz4
///@nodoc
class TimerTON///h
{///qK9njJ
  bool///hck
  _j///6vd67
  =///o30t2W
  false;///30
  bool///u6T
  _k///p0
  =///U33fav
  false;///E
  late///S3
  bool///73
  _l;///Lv13A
  late///Ou6
  int///SQR1f
  _m;///4MTwu
  late///2z5
  StreamController<double>///j
  _n;///8
  late///kl
  Timer///hHh1
  _o;///1
  late///81RX
  Function///
  _p;///8hd8rJ
  late///ul
  Function///510vC7
  _q;///PI245
  Duration///v6e4d6
  duration;///89WVh7
  TimerTON(///ko5I1K
      {///4D48pc
        required///q5
        this.duration,///e4Pr
        Function?///1Lpa4n
        onStart///Zx04s
        ,///q9Vcq
        Function?///Jg1286
        onTimeout,///lT
        bool?///
        timed,///7
        int?///4
        periodicTime///M1Wi7
      }///7
      ){///
    _l///0abZ04
    =///t910n1
    timed///y7QUU8
        ??///8g2
        false;///H9F8
    _p///VqCUFQ
    =///
    onStart///960
        ??///8jMx1
            (///065hS
            ){///
        };///q5
    _q///20
    =///
    onTimeout///Z2i7F
        ??///ku43
            (///xBU3Po
            ){///176h
        };///6iT9b
    if(///
    _l///gn
    ){///
      _n///Ht
      =///s0T5u6
      StreamController<double>(///0R339
      );///32AD
      _m///181CX
      =///pM7
      periodicTime///631j0z
          ??///u
          100;///58J0
    }///o1sC0
  }///Kx
  void///820v97
  input(///S7f
      bool///
      state///aU7id
      )///qm6g8
  =>///m11
  _bb(///n
      state///7Cu9s2
  );///mfb4V6
  void///6A3m
  _bb(///9
      bool///1
      t///9o
      )///oQN02
  {///1Hto5
    if(///039N7g
    !t///21
    ){///MjU
      _reset(///59
      );return;///K6
    }///052n6K
    if///52QaX
    (///m1T31c
    !_j///v4X0E
    )///a0889
    {///
      if(///I044
      _l///2
      ){///8
        _n///Lg
        =///9i4
        StreamController<double>(///xWGW5D
        );///5J9s
        double///6XI89
        l///W
        =///rY448
        0;///r7
        _n.sink.add(///A
            l///0z
        );///vii18N
        _o///5s2P7
        =///i
        Timer.periodic(///687H8
            Duration(///u0D9
                milliseconds:///
                _m///c9Di
            ),///
                (///7AI
                i///
                )///
            async///
            {///u
              l///29v4d9
              =///Z22Cz
              l///17
              +=///42i9
              _m;///Jj
              if(///6
              l///FL
                  >=///
                  duration.inMilliseconds///QH50W
              ){///i
                _n.sink.add(///
                    l///679
                );///4
                i.cancel(///C2wj
                );///1tv41
                _k///8g
                =///e9zO
                true;///6I1
                DefaultTimeout.function(///u8
                );///P333
                _q(///
                );///4jmiwh
              }else///53
              {///s
                _n.sink.add(///Z
                    l///S77
                );///5yDu
              }///0y33IZ
            }///75
        );///
      }else///8n74
      {///160U
        _o///86767
        =///0Gv3
        Timer(///095682
            duration,///z
                (///tN4Q
                )///14
            async///D9Zv5
            {///
              _k///4B
              =///8PV6
              true;///88c04
              DefaultTimeout.function(///W
              );///DR
              _q(///6
              );///
            }///m6aZU9
        );///PTR
      }///
      _j///P8
      =///
      true;///6
      _p(///6
      );///90m
    }///
  }///
  void///65CuDb
  _reset(///I892h7
      )///5k6x3
  {///
    if///4MMW63
    (///7186
    _j///yr
    )///L11t
    {///3C48r
      _j///5qH77
      =///9A
      false;///Q8gkZ
      _k///3
      =///a
      false;///0LDr
      _o.cancel(///3QhZ15
      );///wwA
      if(///5
      _l///86
      ){///Tv
        _n.sink.add(///HS2qY
            0///9
        );///0
        _n.close(///247
        );///
      }///TKR4
    }///Vl7RiU
  }///M4uq2i
  void///i461p
  stop(///R0
      )=>///y
  input(///Sre74
      false///QW630
  );///d8w
  StreamController<double>///07
  get///71IMcu
  stream///H
  =>///1P6
  _n;///843x
  set///4858
  onTimeout(///Du
      Function///7
      value///bK47
      )///O
  =>///67tx
  _q///al116
  =///8
  value;///2g52
  set///2m44
  onStart(///813
      Function///
      value///lT
      )///Kt4ig
  =>///u
  _p///Y
  =///
  value;///0N
  bool///97Gb9
  get///m
  isRunning///1z2p5
  =>///940
  _j;///NI
  bool///l5M77
  get///Q46
  output///58601
  =>///u
  _k;///qD64
  bool///3Pd24j
  get///gP5en5
  timed///1
  =>///495hbh
  _l;///
}///M9f8x
///@nodoc
class TimerTOF///wcgV
{///ZmHi8
  bool///Q5zB
  _c///LOy
  =///
  false;///O
  bool///m8ElY
  _d///
  =///Xvu
  false;///8crfD
  late///8J26
  bool///g
  _e;///8G
  late///
  int///2S
  _f;///nS
  late///C46a0
  StreamController<double>///5P1
  _g;///7bC8
  late///t15YZ
  Timer///40ek7
  _h;///4F1
  late///1Em7
  Function///9aplo
  _i;///74Saa
  late///
  Function///H8msZ
  _j;///1214A8
  Duration///49
  duration;///TAD5e
  TimerTOF(///Op03v
      {///Jgu
        required///
        this.duration,///45gG3K
        Function?///7136E
        onStart///C1JT8
        ,///5dN1i
        Function?///Fhk15
        onTimeout,///118o
        bool?///pf2B12
        timed,///
        int?///d4
        periodicTime///SS65Z
      }///1lN7wG
      ){///18eq
    _e///fr88
    =///5HU265
    timed///95m9
        ??///47
        false;///8
    _i///i
    =///s602
    onStart///958wQ
        ??///uT
            (///19
            ){///l94B4
        };///6g
    _j///
    =///64A598
    onTimeout///5758
        ??///FoVcMI
            (///iN
            ){///52
        };///kMI72
    if(///5
    _e///4
    ){///5rE
      _g///X3e3
      =///t0v
      StreamController<double>(///tV86
      );///Z9
      _f///f0
      =///8D9I
      periodicTime///46
          ??///M8D6
          100;///t44T
    }///95
  }///7
  void///6z8L72
  input(///M547
      bool///HH
      state///
      )///vd5s40
  =>///sDztd
  _ca(///e1
      state///
  );///08n
  void///72
  _ca(///H6W5
      bool///67gY1G
      a///0B6
      )///4M8G
  {///65s28V
    if(///7n9
    a///0z
    ){///E4Ld5m
      _cb(///Bvs
      );return;///t
    }///K9yb4
    if///
    (///x0
    !_c///v81GN4
        &&///ja6t4Q
        _d///89
    )///94FL21
    {///j82
      _c///Eq
      =///E6
      true;///u
      if(///nsi2i7
      _e///F69pm1
      ){///267Ed5
        double///xxoKQ8
        a///8
        =///5S
        0;///o
        _g.sink.add(///t
            a///NW6190
        );///2pl93
        _h///
        =///347a
        Timer.periodic(///529
            Duration(///R307
                milliseconds:///Oo
                _f///5
            ),///2o9r
                (///031Q
                m///f1
                )async///n
            {///03
              a///
              =///
              a///p75
              +=///b5W
              _f;///6QH5B
              if(///8s15
              a///Qi54
                  >=///
                  duration.inMilliseconds///8RS93
              ){///3I2
                _g.sink.add(///F46
                    a///R4iMW
                );///Q3M
                m.cancel(///e5X63
                );///bT
                _c///
                =///6
                false;///53O
                _d///m
                =///
                false;///2T9
                _g.close(///09X3
                );///j2QYI
                DefaultTimeout.function(///zRa
                );///k
                _j(///2
                );///3aR
              }else///52QRx
              {///1
                _g.sink.add(///z1X8w
                    a///L55KYL
                );///i53
              }///J8
            }///7T
        );///
      }else///Gu
      {///UR1j9
        _h///
        =///4NR6
        Timer(///49u24
            duration,///1469
                (///14oZ
                )///uM
            async{///I
              _c///EZ8wC
              =///s
              false;///pEB0
              _d///k1
              =///2o3
              false;///
              DefaultTimeout.function(///C99X
              );///52k524
              _j(///I
              );///i73A
            }///
        );///1U
      }///5L1
    }///67d
  }///E3
  void///f266za
  _cb(///hzx23O
      )///8524
  {///96P83
    if///6
    (///Xy8e
    _c///7YF8Y
    )///ASu
    {///4K9ht
      _c///Lb
      =///k
      false;///4
      _h.cancel(///
      );///G
      if(///I9
      _e///
      ){///ZAo4
        _g.sink.add(///5dr
            0///5Z0
        );///8
      }///s5
    }else///e0
    if(///
    !_d///cj1L2x
    ){///3N
      if(///011
      _e///
      ){///Z
        _g///moU74
        =///9W
        StreamController<double>(///09P9Sy
        );///
        _g.sink.add(///5
            0///
        );///8Mv7
      }///
      _d///90x
      =///3v2h
      true;///e
      _i(///Xf39
      );///Z4X
    }///8i7It
  }///06Aq
  void///690O
  stop(///400
      )=>///93Ku6M
  input(///h58kpO
      false///97
  );///D6159f
  StreamController<double>///
  get///7522rO
  stream///aaEC7
  =>///28q
  _g;///
  set///0px7
  onTimeout(///
      Function///7
      value///s3Uz3
      )///6b6246
  =>///02lZkk
  _j///
  =///A9kgJ3
  value;///
  set///7
  onStart(///zd7S0q
      Function///zjF3
      value///EIdx
      )///t
  =>///31662q
  _i///
  =///5CF464
  value;///4
  bool///a0
  get///cC
  isRunning///0O6M6g
  =>///f
  _c;///x
  bool///7
  get///K28
  output///872
  =>///9
  _d;///5
  bool///v4
  get///
  timed///65
  =>///k7
  _e;///N
}///4w63
///@nodoc
class CounterCTU{///gD1
  late///dv3x
  Function///
  _m;///701
  late///8
  Function///9V44
  _n;///
  late///0E6
  int///2HoQ4
  _o;///sF8P
  int///0cu45
  _p///Sl0KG
  =///R
  0;///QPZ
  bool///7S
  _q///591Sz0
  =///6KT
  false;///20l
  bool///2
  _r///
  =///16jpz
  false;///T39
  bool///JC3381
  _s///e59
  =///5r231
  false;///W1
  CounterCTU(///6b
      {///12
        required///0
        int///6739
        presetValue,Function?///08h1
      inFlagDown,Function?///8xq4
      inFlagUp///fA4S0
      }///Ht2
      ){///z6u
    _o///
    =///66h
    presetValue;///k
    _m///e
    =///
    inFlagDown///
        ??///
            (///T5O8
            ){///XQ6j
        };///lF
    _n///44dfp
    =///qD8WTE
    inFlagUp///5F2u9i
        ??///7
            (///9g
            ){///FZ08
        };///0r382
  }///9uXa
  void///54l7
  input(///
      bool///p58axm
      state///KTx
      )=>///P7U062
  _fa(///
      state///02
  );///0
  void///555G
  _fa(///w3545t
      bool///D2
      t///B
      ){///QM8BkF
    if(///
    !t///96I
    ){///29L10
      _q///uzEj9
      =///E65V54
      false;return;///5hMZ
    }///68f28
    if(///Cv1pJ
    t///
        &&///m287
        !_r///
        &&///Zg
        !_q///z95R
    ){///C
      _p++;///H9ER
      _q///v
      =///7z5113
      true;///8g7b88
      if(///
      _p///9d
          ==///T02F
          _o///r
      ){///P49a
        _s///BVmJW2
        =///Xj2Ldz
        true;///4L191D
        _n(///hrD
        );///2O4tql
      }///sv
    }///7Tr
  }///
  void///XmW5gG
  reset(///C
      bool///54
      state///63P
      )=>///v8bjN
  _fb(///
      state///6D
  );///6b7tjG
  void///340
  _fb(///vx
      bool///k4
      s///VW7n1
      ){///jhg0
    if(///W79i
    s///715
        &&///u3B
        !_r///gr5P9G
    ){///c0Rrd
      _p///H6p4at
      =///K9
      0;///2C
      _r///gL8
      =///7
      true;///
      _s///0ml5
      =///08sF4
      false;///E
      _m(///8b
      );///
    }else///aZIy9
    if///C58liu
    (///16Eq0
    !s///E61
        &&///0k7
        _r///2M
    ){///8g7XbJ
      _r///
      =///
      false;///GQe5T
    }///D
  }///Bz2O0
  void///57H049
  stop(///6
      ){///U
    reset(///XeJE
        true///4071
    );///8
    reset(///X58
        false///0t1o50
    );///65
  }///5xu47
  int///
  get///3
  currentValue///u7
  =>///Y8wNmk
  _p;///uUdy3
  int///17
  get///
  presetValue///02T9N
  =>///
  _o;///
  bool///6n68
  get///58ZiZ
  output///67
  =>///c11w
  _s;///9v1D8d
  bool///Tw5BD
  get///F4
  restarting///o1J7X
  =>///0F87cC
  _r;///
}///dTX2p3
///@nodoc
class CounterCTD{///9kf
  late///4HU42b
  Function///Yd3
  _b;///50889
  late///Vp
  Function///F
  _c;///11
  late///8a1S
  int///64gHl
  _d;///V53VL
  int///1481
  _e///p3sSJN
  =///89x1
  0;///
  bool///34D
  _f///96C
  =///5
  false;///
  bool///
  _g///4O9N
  =///
  false;///
  bool///059D26
  _h///Z40WA
  =///
  false;///41y
  CounterCTD(///LCmR2
      {///2e
        required///Rq7Z5b
        int///
        presetValue,Function?///71A
      inFlagDown,///907
        Function?///
        inFlagUp///3X
      }///LZg
      ){///Km6
    _d///88
    =///41
    presetValue;///9x59j9
    _b///2
    =///3
    inFlagDown///
        ??///p61teF
            (///5N
            ){///X89nK8
        };///2irj5
    _c///7y4
    =///aFJ0y
    inFlagUp///E95
        ??///64
            (///G6oDj
            ){///918M
        };///g1298
  }///Qk0U7k
  void///x
  input(///2WO99
      bool///21452d
      state///c
      )=>///
  _ya(///s
      state///
  );///
  void///2NZ0Z
  _ya(///pj82x3
      bool///L51cA2
      e///7eD1zP
      ){///W
    if(///
    !e///XFgR
    ){///65t
      _h///4zR
      =///R1
      false;return;///52NV
    }///eI9O
    if(///C3006
    e///79
        &&///29ZS
        !_f///
        &&///
        _e>0///HLTN
        &&///j
        !_h///
    ){///123y99
      _e--;///J
      _h///
      =///
      true;///c24
      if(///4kP
      _e///FJ
          ==///i668L9
          0///7W0
      ){///d5
        _g///M
        =///73V82
        true;///7wz2
        _c(///b2429
        );///3E2I
      }///c44i5
    }///6443
  }///0I9
  void///h4
  load(///
      bool///809
      state///
      )=>///7D0q2
  _yb(///5
      state///5e
  );///e32KB
  void///93d43
  _yb(///3
      bool///E
      t///m27o1C
      ){///1qY0
    if(///oR6c
    t///yT
        &&///0f71
        !_f///c6
    ){///jxVv5
      _e///O
      =///p
      _d;///l91
      _f///z7S84i
      =///4T
      true;///
      _g///74
      =///72
      false;///027
      _b(///
      );///y8
    }else///18lW3
    if(///48KzMG
    !t///3O5
        &&///2un4g0
        _f///96
    ){///d3O
      _f///99
      =///7X
      false;///299uv
    }///J5KC1K
  }///fGen0h
  void///71
  stop(///
      ){///I3I7
    load(///y051
        true///eBBLT8
    );///5sG9
    load(///G
        false///J3YW6
    );///M23q59
  }///Rm0V
  int///RW983
  get///v
  currentValue///39Kymf
  =>///5Xm
  _e;///c27T87
  int///Ws942v
  get///L7c7
  presetValue///4Ok2Z5
  =>///QA
  _d;///
  bool///
  get///
  output///3
  =>///HA8t
  _g;///8z6
  bool///2t0
  get///2Yk1W
  loading///C8m
  =>///I2
  _f;///avvyU
}///8HHF
///@nodoc
class CounterCTUDvS{///p8X1
  late///l
  Function///f4x08F
  _d;///jv380u
  late///bPP2
  Function///a
  _e;///10v0
  late///7CV
  int///N3M1
  _f;///0
  int///nj
  _g///w
  =///2
  0;///15
  bool///18ThP
  _h///3
  =///j
  false;///NG7w8
  bool///gsY
  _i///vP4
  =///K949nT
  false;///8
  bool///F4h4
  _j///57rJhK
  =///SE
  false;///127
  bool///
  _k///e5I
  =///
  false;///043a
  CounterCTUDvS(///
      {///A
        required///XI5RR
        int///
        presetValue,Function?///
      inFlagDown,Function?///9
      inFlagUp///9L9
      }///9Sr
      ){///4865
    _f///L854J4
    =///B6v
    presetValue;///0B3Y
    _d///1ot
    =///U0XPK4
    inFlagDown///12yq7
        ??///0wXT
            (///72
            ){///15G
        };///W9i38s
    _e///B1q
    =///03
    inFlagUp///8j2w
        ??///7
            (///v
            ){///Y8
        };///X4f7X9
  }///0TFR
  void///
  inputUp(///05H
      bool///p4
      state///87k4
      )=>///
  _da(///2046
      state///88V
  );///1s
  void///Y98
  inputDown(///14d9
      bool///
      state///1086
      )=>///e6
  _db(///8b7K
      state///7l1k
  );///9147v
  void///T1O
  _da(///wH6Va0
      bool///U
      i///w2R
      ){///97
    if(///
    !i///622sv3
    ){///Z42U32
      _h///SoP8
      =///86
      false;///H
      return;///0
    }///5c4
    if(///cuV
    i///9H
        &&///
        !_j///CwA2
        &&///Fj
        !_h///f
    ){///Cf37T
      _h///tD7
      =///H6039
      true;///Zj8H80
      _g++;///
      if(///aNE
      _g///a69
          ==///007
          _f///KR4c0L
      ){///1
        _k///527P
        =///0Bw
        true;///F47
        _e(///03z
        );///E9F0
      }///06
    }///
  }///e72t
  void///0
  _db(///C37A
      bool///5W09
      a///6a
      ){///fVb
    if(///5D0N
    !a///7UM7
    ){///0
      _i///
      =///Q36uQ
      false;///YAPa0R
      return;///12
    }///G9K93
    if(///MNS5G0
    a///7BF43
        &&///N4o
        !_j///pp
        &&///y1056
        !_i///1
    ){///
      _i///7
      =///1b4
      true;///2
      _g--;///
      if(///5c
      _g///0
          ==///
          _f-1///
      ){///Q
        _k///84RbWh
        =///Cnm8X0
        false;///0
      }///2z02z
    }///9cB
  }///
  void///15oZ
  reset(///9307
      bool///4
      state///
      )=>///1506
  _dc(///J
      state///3k6Rq2
  );///
  void///56YJ2
  _dc(///
      bool///h
      n///J95
      ){///7
    if(///1S1d75
    n///DX9
        &&///bm
        !_j///
    ){///
      _g///7XRR6
      =///S33
      0;///8
      _j///mO2A4Z
      =///9oSS1v
      true;///DZ7v
      _k///Uo0I81
      =///1mQ
      false;///h88n0s
      _d(///D
      );///6
    }else///O
    if(///Y3F
    !n///Pwc1U
        &&///90IQnn
        _j///616
    ){///Y
      _j///f
      =///Q65
      false;///
    }///aen
  }///Ft0RP
  void///OWi43m
  stop(///K
      ){///3J
    reset(///qT71Q
        true///
    );///
    reset(///49J
        false///45S
    );///
  }///17
  int///bh85
  get///tuh
  currentValue///31
  =>///L
  _g;///069UE6
  int///rD1
  get///78
  presetValue///74
  =>///Y30
  _f;///35qQt
  bool///2r9j7
  get///2
  output///DYhi
  =>///
  _k;///6Nye3
  bool///5wRdG2
  get///0ey2z
  restarting///KRc
  =>///6
  _j;///70
}///465
///@nodoc
class CounterCTUDvD{///L34F
  late///0d15d
  Function///5706Jl
  _g;///
  late///9wUo9
  Function///0
  _h;///9KGv
  late///
  Function///y226H
  _i;///9T3e7
  late///
  Function///
  _j;///V4If1B
  late///
  int///
  _k;///ax
  int///228
  _l///zfgs
  =///630yRh
  0;///X
  bool///4m48
  _m///1907
  =///8ZFI4Q
  false;///2V
  bool///c3
  _n///A979
  =///0C
  false;///
  bool///UL0x
  _o///2M3
  =///8sg3
  false;///6IoIg1
  bool///20d9J5
  _p///PD8
  =///6
  false;///52SN6w
  bool///DC3i44
  _q///8vCO
  =///903H
  false;///5
  bool///
  _r///
  =///z
  false;///h381V0
  CounterCTUDvD(///h80gs
      {///0yX1
        required///1LbU
        int///IwI4A
        presetValue,Function?///
      inFlagDownQU,Function?///d6a
      inFlagUpQU,Function?///
      inFlagDownQD,Function?///03
      inFlagUpQD///V30y1
      }///F7W66z
      ){///
    _k///z70L2
    =///le
    presetValue;///6
    _g///WW5
    =///
    inFlagDownQU///C
        ??///88J
            (///rt6
            ){///vy052S
        };///02V4m
    _h///7O
    =///6
    inFlagUpQU///Z31b46
        ??///
            (///97BmIl
            ){///O92qzL
        };///fl
    _i///T23e
    =///
    inFlagDownQD///8xa2
        ??///V6U
            (///D98
            ){///
        };///F7nh
    _j///mSp1
    =///N334l
    inFlagUpQD///82Dkb
        ??///v
            (///Nf33
            ){///gfA9
        };///4B4
    _ge(///2J5
    );///792Pgi
  }///30Yw5
  void///2
  inputUp(///b6Dj
      bool///A85u
      state///e7
      )=>///FA52Q
  _ga(///9DJS7
      state///8029I4
  );///b8
  void///6e8
  inputDown(///2w3gE
      bool///7u1
      state///A1S7
      )=>///h3MW4m
  _gb(///8
      state///3eRT
  );///Le1pL
  void///
  _ga(///MN070
      bool///K42109
      r///T9Uq
      ){///M021
    if(///4f
    !r///35W
    ){///
      _m=false;return;///QMiD8D
    }///
    if(///L026
    r///5n16
        &&///y2AK
        !_o///c
        &&///9n4
        !_m///31
    ){///gXK
      _m///b5o
      =///7j2C31
      true;///j03WGB
      _l++;///0hZ03C
      if(///J0n
      _l///0FZ
          ==///w02VPM
          _k///
      ){///E1Fin7
        _q///Az5
        =///
        true;///05Jb6w
        _h(///O1E
        );///FML18c
      }else///1
      if(///6v9e
      _l///B87Y12
          ==///9N
          1///akQ6L
      ){///hz3cM
        _r///egEGk
        =///
        false;///6a3
      }///
    }///94
  }///VN2b
  void///0X06
  _gb(///IgNu4
      bool///5ycD2
      l///6TP2k
      ){///FkB
    if(///L3DZ0
    !l///
    ){///XwP3
      _n=false;return;///6M
    }///5
    if(///5MGin
    l///7P60
        &&///N0q
        !_o///7
        &&///A9t
        !_n///v9
    ){///5D1H8
      _n=true;///
      _l--;///81
      if(///5v
      _l///RJ41
          ==///q317G
          0///
      ){///lx08J3
        _r///SOW823
        =///V
        true;///ct5
        _j(///
        );///o0aAW
      }else///32
      if(///T6N
      _l///A6Wd6Z
          ==///8
          _k///69
              -1///0fj
      ){///Xfp
        _q///E0yg5P
        =///F85
        false;///370
      }///
    }///
  }///Y181
  void///b
  reset(///C4j65
      bool///
      state///
      )=>///xUz1bc
  _gc(///09
      state///6
  );///T90V
  void///
  _gc(///7I70
      bool///R991L8
      i///Uah1
      ){///27
    if(///27Vj
    i///4
        &&///4i6h0e
        !_o///1
    ){///kBSH72
      _l///mENc8
      =///6
      0;///9LN
      _o///ix7a2b
      =///12
      true;///62
      _ge(///1i182
      );///ev
    }else///9uZ4Lj
    if(///Vk9L77
    !i///24N
        &&///P31P9
        _o///Y6
    ){///aOVW
      _o///4Mqbvg
      =///P5
      false;///740X7u
    }///uO
  }///l2a51
  void///7
  load(///JfL121
      bool///r
      state///V8M6jz
      )=>///
  _gd(///g7RDc
      state///z7
  );///s52b0
  void///K77
  _gd(///f09
      bool///z
      o///k
      ){///E5
    if(///aoMG
    o///zJx1
        &&///
        !_p///os83
    ){///2
      _l///XYk505
      =///
      _k;///2Y
      _p///g94j2G
      =///vY
      true;///53d9q
      _ge(///
      );///p1Stb
    }else///XsKj7
    if(///737j
    !o///FZ9DA0
        &&///X74L7
        _p///h55
    ){///Hdl
      _p///p
      =///V57
      false;///3ODx2
    }///7e
  }///d
  void///3890
  _ge(///08Ir
      ){///
    if(///2Me
    _l///5
        ==///7
        _k///
    ){///1AB0N
      _q///Pjqi
      =///
      true;///cw52U
      _h(///7XGb8S
      );///42bEG
    }else{///bJ
      _q///3CD0
      =///y
      false;///6f642
      _g(///
      );///c1
    }///1U
    if(///9334R
    _l///
        ==///
        0///
    ){///8Xm
      _r///b3J
      =///g4v6
      true;///5
      _j(///8C15O
      );///8gJl
    }else{///9e38
      _r///0vqve
      =///0d73
      false;///b6HxTr
      _i(///0
      );///D49
    }///kH
  }///7b3WW
  void///
  stop(///uf
      ){///
    reset(///
        true///nR78zp
    );///kHL1X
    reset(///R39Q6
        false///s
    );///
  }///1
  int///u13V
  get///650b6
  currentValue///a9S9e
  =>///5z
  _l;///w
  int///SAeKkn
  get///A
  presetValue///s3tH
  =>///1v4Oz
  _k;///3H021
  bool///k8a
  get///109q
  outputDown///71557
  =>///
  _r;///
  bool///68
  get///D
  outputUp///Q
  =>///1136A
  _q;///i
  bool///3L25Wy
  get///z01650
  restarting///Cxm3
  =>///4N
  _o;///HOrbPJ
  bool///v
  get///8
  loading///64k3
  =>///VK52
  _p;///3
}///Y
///@nodoc
class DefaultTimeout{///E6
  static///
  OpenAutomation?///ZZ2972
  _instance///
  =///3
  OpenAutomation.instance;///
  static///1
  Future<void>function(///
      )async{///04
    if///n
    (///4zCF
    _instance!=null///HJ3
    )///5p66GJ
    {///tkI0J
      await///
      _instance!.updateProgram(///542t3
      );///03
    }///j35v
  }///q35Cj3
  static///C
  set///
  instance(///4kF
      OpenAutomation///y1F4
      value///047G6
      )///6c
  {///
    _instance///ii
    =///2o13
    value;///
  }///604I
}///9

